function defence_anc_all_in_one()
%% DEFENCE_ANC_ALL_IN_ONE  AI/ML-enabled adaptive noise cancellation for defence audio
%  SIH 2026 - Problem Statement 26052 (DRDO)
%
%  Removes stationary (engine / rotor hum), non-stationary (missile whine,
%  helicopter, sirens) and impulsive (gunshots, machine-gun fire,
%  explosions) noise from speech, plays the result and reports SNR, STOI
%  and PESQ.
%
%  Just press F5 / type  defence_anc_all_in_one  in the MATLAB command window.
%  No toolboxes are required (tested with MATLAB-compatible GNU Octave 8).
%
%  PART 1  cleans your recordings (audio/noisy/*), saves them to results/,
%          plays "before" and "after" and plots the spectrograms.
%          A real recording has no clean reference, so SNR is *estimated*
%          blindly there (STOI / PESQ need the clean speech by definition).
%  PART 2  measures true SNR / STOI / PESQ: known clean speech is mixed with
%          defence noise at a known SNR, cleaned, and compared with the clean
%          original (the evaluation protocol of the problem statement).
%  (single-file bundle generated by tools/make_single_file.py - identical
%   code to main_defence_anc.m + src/*; keep models/defence_gru.mat next
%   to this file or in ./models to enable the AI/ML stage)

close all; clc;

root = fileparts(mfilename('fullpath'));

%% ------------------------------- settings --------------------------------
input_files = { fullfile('defence_sound.mp3'), ...
                fullfile('defence_soundMG1.mp3') };
clean_reference = '';     % optional: the clean speech contained in input_files{1}
                          % (if you created the noisy file yourself) -> exact metrics
play_audio  = true;       % listen to before / after
make_plots  = true;
out_dir     = fullfile(root, 'results');
test_snrs   = [0 5];      % PART 2 input SNRs (dB)
test_noises = {'battlefield', 'machinegun', 'gunshot', 'helicopter', 'missile'};

%% ------------------------------ the filter --------------------------------
p = anc_params();                  % all tunable parameters (see anc_params.m)
p.model = dnn_load();              % trained GRU mask estimator (models/)
if isempty(p.model)
    fprintf('Model file not found -> using the statistical OM-LSA filter only.\n');
    p.use_dnn = false;
end
if ~exist(out_dir, 'dir'), mkdir(out_dir); end

%% ============== PART 1 : clean the supplied recordings =====================
for i = 1:numel(input_files)
    [x, fs] = read_audio(input_files{i});
    [y, fs_y, info] = defence_anc(x, fs, p);            % <-- noise cancellation

    [~, name, ext] = fileparts(input_files{i});
    out_file = fullfile(out_dir, [name '_enhanced.wav']);
    audiowrite(out_file, y, fs_y);

    xm = resample_k(mean(x, 2), fs_y, fs);             % noisy input @16 kHz
    xm = xm(1:numel(y));
    b = blind_snr(xm, y, fs_y);

    fprintf('\n=================================================================\n');
    fprintf(' %s  (%.1f s, %s, %d Hz)\n', [name ext], ...
            size(x, 1) / fs, info.mode, fs);
    fprintf('=================================================================\n');
    fprintf(' latency %.0f ms | real-time factor %.3f | saved: %s\n', ...
            info.latency_ms, info.rtf, out_file);
    fprintf(' Estimated SNR (no clean reference): input %6.1f dB  ->  output %6.1f dB\n', ...
            b.snr_in, b.snr_out);
    fprintf(' Background noise reduction in speech pauses: %.1f dB\n', b.noise_reduction);

    if i == 1 && ~isempty(clean_reference)
        [c, fc] = read_audio(clean_reference);
        c = resample_k(mean(c, 2), fs_y, fc);
        n = min([numel(c) numel(y)]);
        report_metrics('Your recording (with clean reference)', c(1:n), xm(1:n), y(1:n), fs_y);
    end

    if make_plots
        try
            plot_spectrograms(xm, y, fs_y, [name ext]);
            drawnow;
        catch
            fprintf(' (plotting not available on this system)\n');
        end
    end
    if play_audio
        play_audio_file(xm, fs_y, 'ORIGINAL (noisy)');
        play_audio_file(y, fs_y, 'ENHANCED');
    end
end

%% ========= PART 2 : SNR / STOI / PESQ with known clean speech =============
% clean test speech: CMU ARCTIC utterances (male + female, not used in training)
cf = dir(fullfile(root, 'audio', 'clean', '*.wav'));
spk = {'aew', 'axb'};
fprintf('\n\n######## Objective evaluation (clean speech + defence noise) ########\n');
fprintf('%-12s %5s | %-22s | %-24s | %-22s | %-22s\n', 'noise', 'SNRin', ...
        'SNR (dB) noisy->enh', 'STOI noisy->enh', 'PESQ-WB noisy->enh', 'PESQ-NB noisy->enh');
fprintf('%s\n', repmat('-', 1, 124));
T = [];
for iz = 1:numel(test_noises)
    for s_in = test_snrs
        for k = 1:numel(spk)
            files = cf(~cellfun(@isempty, strfind({cf.name}, spk{k})));
            clean = [];
            for j = 1:numel(files)
                [c, fc] = audioread(fullfile(files(j).folder, files(j).name));
                clean = [clean; zeros(round(0.3 * fc), 1); resample_k(c(:, 1), 16000, fc)]; %#ok<AGROW>
            end
            clean = clean / max(abs(clean)) * 0.5;
            noise = defence_noise(test_noises{iz}, numel(clean) / 16000, 16000, 7 + iz + 10 * k);
            noisy = mix_at_snr(clean, noise, s_in);
            enh = defence_anc(noisy, 16000, p);
            r = [evaluate_pair(clean, noisy, 16000), evaluate_pair(clean, enh, 16000)];
            T = [T; iz, s_in, k, r]; %#ok<AGROW>
        end
        rows = T(T(:, 1) == iz & T(:, 2) == s_in, 4:end);
        mm = mean(rows, 1);          % [snr stoi pesqwb pesqnb] noisy, then enhanced
        fprintf('%-12s %+5d | %8.2f -> %8.2f  | %8.3f -> %8.3f     | %7.2f -> %7.2f     | %7.2f -> %7.2f\n', ...
                test_noises{iz}, s_in, mm(1), mm(5), mm(2), mm(6), mm(3), mm(7), mm(4), mm(8));
    end
end
fprintf('%s\n', repmat('-', 1, 124));
for s_in = test_snrs
    mm = mean(T(T(:, 2) == s_in, 4:end), 1);
    fprintf('%-12s %+5d | %8.2f -> %8.2f  | %8.3f -> %8.3f     | %7.2f -> %7.2f     | %7.2f -> %7.2f\n', ...
            'AVERAGE', s_in, mm(1), mm(5), mm(2), mm(6), mm(3), mm(7), mm(4), mm(8));
end
fprintf('\nTargets (problem statement): SNR > 15 dB, STOI > 0.85, PESQ > 2.5\n');
end

% ========================================================================
% src/anc/anc_init.m
% ========================================================================
function st = anc_init(p)
%ANC_INIT  Create the state of the streaming (real-time) noise canceller.
%
%   st = anc_init(anc_params())
%
%   The state holds the STFT buffers and all adaptive quantities.  Feed it
%   with anc_process_frame() one hop (8 ms = 128 samples @ 16 kHz) at a time.

    st.p   = p;
    st.N   = round(p.frame_ms * p.fs / 1000);          % 512
    st.R   = round(p.hop_ms * p.fs / 1000);            % 128
    st.K   = st.N / 2 + 1;                             % 257 bins
    n      = (0:st.N-1)';
    st.win = sqrt(0.5 - 0.5 * cos(2 * pi * n / st.N)); % sqrt-Hann (periodic)
    st.ola_norm = st.R / sum(st.win.^2);               % = 0.5 for 75 % overlap
    st.inbuf  = zeros(st.N, 1);
    st.outbuf = zeros(st.N, 1);
    st.frame  = 0;
    f = (0:st.K-1)' * p.fs / st.N;
    st.freq = f;

    % per-frame smoothing constants (parameters are given per 16 ms / 8 ms)
    hop_ratio = p.hop_ms / 16;
    st.a_psd  = p.spp_alpha_psd ^ hop_ratio;
    st.a_p    = p.spp_alpha_p ^ hop_ratio;
    st.n_init = max(1, round(p.init_ms / p.hop_ms));

    % SPP-MMSE noise tracker (Gerkmann & Hendriks, IEEE TASLP 2012)
    xi_h1 = 10^(p.spp_xi_h1_db / 10);
    st.prior_fact   = 1;                       % P(H0)/P(H1) = 1
    st.log_glr_fact = log(1 / (1 + xi_h1));
    st.glr_exp      = xi_h1 / (1 + xi_h1);
    st.lambda_s     = zeros(st.K, 1);
    st.PH1mean      = 0.5 * ones(st.K, 1);

    % transient (impulsive) noise stage
    st.tr_bins  = find(f >= p.tr_band_hz(1) & f <= p.tr_band_hz(2));
    st.a_ref    = exp(-p.hop_ms / p.tr_ref_ms);
    st.hold_dec = 10^(-p.tr_hold_db_s * p.hop_ms / 1000 / 10);
    st.tr_max   = round(p.tr_max_ms / p.hop_ms);
    st.Rref     = zeros(st.K, 1);
    st.Rhold    = zeros(st.K, 1);
    st.tr_count = 0;
    st.pt       = 0;

    % tonal stage
    % a continuously present peak reaches ton_thresh after ton_persist_ms
    st.a_ton    = (1 - p.ton_thresh) ^ (p.hop_ms / p.ton_persist_ms);
    st.T        = zeros(st.K, 1);
    st.ton_ok   = (f >= 150 & f <= 7800);
    st.med_idx  = min(max(repmat((1:st.K)', 1, 17) + repmat(-8:8, st.K, 1), 1), st.K);

    % zero-phase spectral low-cut (rumble, wind, helicopter rotor)
    st.lowcut = ones(st.K, 1);
    st.lowcut(f < p.lowcut_hz) = 10^(p.lowcut_db / 20);

    % gain stage
    st.a_dd   = p.dd_alpha;
    st.xi_min = 10^(p.xi_min_db / 10);
    st.qfac   = p.q_absence / (1 - p.q_absence);
    st.gmin   = 10^(p.gmin_db / 20);
    st.A2prev = zeros(st.K, 1);

    % AI/ML stage (GRU mask estimator), if a model is supplied
    st.dnn = [];
    if isfield(p, 'model') && ~isempty(p.model)
        st.dnn = p.model;
        st.h = zeros(st.dnn.H, 1);
        st.dnn_floor = 10^(p.dnn_floor_db / 20);
    end

    % statistics for reporting
    st.stat_tr_frames = 0;
    st.stat_ton_frames = 0;
end

% ========================================================================
% src/anc/anc_params.m
% ========================================================================
function p = anc_params(varargin)
%ANC_PARAMS  Default parameters of the hybrid adaptive noise canceller.
%
%   p = anc_params()                     defaults
%   p = anc_params('name', value, ...)   override individual fields
%
%   All time constants are specified for the default 16 kHz / 8 ms hop and
%   are converted to per-frame values inside anc_init.m.

    % ---- framework -------------------------------------------------------
    p.fs        = 16000;   % processing rate (Hz)
    p.frame_ms  = 32;      % STFT frame (algorithmic latency)
    p.hop_ms    = 8;       % hop size (75 % overlap)

    % ---- stage 1: pre-filter --------------------------------------------
    p.dc_block  = true;    % 1st-order DC blocker (~10 Hz, negligible phase)
    p.lowcut_hz = 70;      % zero-phase spectral low-cut for rumble / wind
    p.lowcut_db = -30;     % attenuation below lowcut_hz

    % ---- AI/ML stage: causal GRU mask estimator --------------------------
    p.use_dnn      = true;   % use models/defence_gru.mat if it exists
    p.model_file   = '';     % '' = default location
    p.dnn_floor_db = -30;    % lowest gain applied by the network mask

    % ---- stage 2: stationary noise tracker (SPP-MMSE) ---------------------
    p.spp_xi_h1_db   = 15;     % fixed a-priori SNR under speech presence
    p.spp_alpha_psd  = 0.80;   % PSD smoothing  (per 16 ms)
    p.spp_alpha_p    = 0.90;   % SPP smoothing  (per 16 ms)
    p.init_ms        = 64;     % initial noise estimate from first frames

    % ---- stage 3: impulsive noise (gunshot / MG / explosion) ------------
    p.transient       = true;
    p.tr_band_hz      = [300 7000];  % detection band
    p.tr_quantile     = 0.30;   % fraction of bins that may NOT rise
    p.tr_on_db        = 5.0;    % broadband rise => transient
    p.tr_off_db       = 1.5;    % rise below this => no transient
    p.tr_min_excess_db= 6.0;    % frame must exceed stationary noise by this
    p.tr_ref_ms       = 24;     % reference (speech + noise) smoothing
    p.tr_hold_db_s    = 40;     % decay of the peak-hold reference (dB/s)
    p.tr_max_ms       = 400;    % max. duration before reference re-adapts
    p.tr_over         = 1.0;    % over-subtraction of the transient PSD
    p.tr_mode         = 'suppress';  % 'suppress' or 'restore'

    % ---- stage 4: tonal noise (whine, sirens, rotor / engine hum) -------
    p.tonal           = true;
    p.ton_peak_db     = 9;      % peak-to-local-median ratio
    p.ton_persist_ms  = 400;    % time to confirm a persistent tone
    p.ton_thresh      = 0.6;    % persistence threshold (0..1)
    p.ton_width       = 2;      % notch half-width (bins)

    % ---- stage 5: OM-LSA gain -------------------------------------------
    p.dd_alpha       = 0.96;    % decision-directed smoothing (per 8 ms)
    p.xi_min_db      = -25;     % a-priori SNR floor
    p.q_absence      = 0.5;     % a-priori speech absence probability
    p.gmin_db        = -20;     % residual floor re. stationary noise level
    p.gain_smooth    = true;    % cross-frequency smoothing of the gain

    % ---- stage 6: optional reference-microphone NLMS ANC ------------------
    p.nlms_taps      = 256;     % 16 ms adaptive FIR
    p.nlms_mu        = 0.3;
    p.nlms_vad_gate  = true;    % freeze adaptation during speech

    % ---- output ---------------------------------------------------------
    p.out_peak       = 0.95;    % peak normalisation limit (full scale = 1)

    for i = 1:2:numel(varargin)
        p.(varargin{i}) = varargin{i+1};
    end
end

% ========================================================================
% src/anc/anc_process_frame.m
% ========================================================================
function [out, st] = anc_process_frame(xin, st)
%ANC_PROCESS_FRAME  Process one hop of audio (real-time / streaming core).
%
%   [out, st] = anc_process_frame(xin, st)
%
%   xin : st.R new input samples (column)      out : st.R output samples
%   The output is delayed by st.N - st.R samples (24 ms) w.r.t. the input;
%   total algorithmic latency is one frame (32 ms).
%
%   Per frame:
%     1. STFT analysis (sqrt-Hann, 75 % overlap)
%     2. stationary noise PSD      - SPP-based MMSE tracker
%     3. impulsive noise PSD       - broadband-onset detector + excess over
%                                    a peak-hold speech/noise reference
%     4. tonal noise PSD           - persistent narrow-band peak tracker
%     5. OM-LSA gain               - MMSE log-spectral amplitude estimator,
%                                    decision-directed a-priori SNR, speech
%                                    presence weighting, noise-relative floor
%     6. ISTFT overlap-add

    p = st.p;
    K = st.K;
    st.frame = st.frame + 1;

    % ---- 1. analysis ------------------------------------------------------
    st.inbuf = [st.inbuf(st.R+1:end); xin(:)];
    Yf = fft(st.inbuf .* st.win);
    Y  = Yf(1:K);
    P  = max(real(Y).^2 + imag(Y).^2, 1e-12);

    % ---- 2. stationary noise tracker ------------------------------------
    if st.frame <= st.n_init
        st.lambda_s = st.lambda_s + (P - st.lambda_s) / st.frame;
        if st.frame == 1
            st.Rref = P;  st.Rhold = P;
        end
    else
        snr_post = P ./ st.lambda_s;
        glr = st.prior_fact * exp(min(st.log_glr_fact + st.glr_exp * snr_post, 200));
        ph1 = glr ./ (1 + glr);
        st.PH1mean = st.a_p * st.PH1mean + (1 - st.a_p) * ph1;
        stuck = st.PH1mean > 0.99;
        ph1(stuck) = min(ph1(stuck), 0.99);
        est = ph1 .* st.lambda_s + (1 - ph1) .* P;
        st.lambda_s = st.a_psd * st.lambda_s + (1 - st.a_psd) * est;
    end
    lam_s = max(st.lambda_s, 1e-12);

    % ---- AI/ML stage: GRU mask estimator (replaces steps 3-5) -------------
    if ~isempty(st.dnn)
        [m, st.h] = dnn_mask_step(P, lam_s, st.h, st.dnn);
        st.last_mask = m;
        G = max(m, st.dnn_floor) .* st.lowcut;
        S  = G .* Y;
        fr = real(ifft([S; conj(S(K-1:-1:2))])) .* st.win;
        st.outbuf = st.outbuf + fr;
        out = st.outbuf(1:st.R) * st.ola_norm;
        st.outbuf = [st.outbuf(st.R+1:end); zeros(st.R, 1)];
        return;
    end

    % ---- 3. impulsive (transient) noise ---------------------------------
    lam_t = zeros(K, 1);
    Yuse = Y;
    Puse = P;
    pt = 0;
    if p.transient && st.frame > 1
        b = st.tr_bins;
        rise = sort(10 * log10(P(b) ./ max(st.Rhold(b), 1e-12)));
        Q = rise(max(1, round(p.tr_quantile * numel(b))));
        excess = 10 * log10(sum(P(b)) / sum(lam_s(b)));
        if excess >= p.tr_min_excess_db
            pt = min(max((Q - p.tr_off_db) / (p.tr_on_db - p.tr_off_db), 0), 1);
        end
        if pt > 0
            if strcmp(p.tr_mode, 'restore')
                lim = sqrt(min(1, p.tr_over * st.Rref ./ P));
                fac = (1 - pt) + pt * lim;
                Yuse = Y .* fac;
                Puse = P .* fac.^2;
            else
                lam_t = pt * max(P - p.tr_over * st.Rref, 0);
            end
        end
    end
    if pt < 0.5 || st.tr_count > st.tr_max
        st.Rref = st.a_ref * st.Rref + (1 - st.a_ref) * P;
    end
    st.Rhold = max(st.Rref, st.Rhold * st.hold_dec);
    if pt >= 0.5
        st.tr_count = st.tr_count + 1;
        st.stat_tr_frames = st.stat_tr_frames + 1;
    else
        st.tr_count = 0;
    end
    st.pt = pt;

    % ---- 4. tonal noise (persistent narrow-band peaks) --------------------
    lam_tone = zeros(K, 1);
    if p.tonal
        med = median(Puse(st.med_idx), 2);
        pk = (Puse > med * 10^(p.ton_peak_db / 10)) & st.ton_ok & ...
             (Puse >= [Puse(2:end); 0]) & (Puse >= [0; Puse(1:end-1)]);
        Td = max([st.T, [0; st.T(1:end-1)], [st.T(2:end); 0]], [], 2);
        st.T = pk .* (st.a_ton * Td + (1 - st.a_ton)) + (~pk) .* (0.85 * st.T);
        tone = pk & (st.T > p.ton_thresh);
        if any(tone)
            w = p.ton_width;
            msk = conv(double(tone), ones(2*w+1, 1), 'same') > 0;
            lam_tone(msk) = Puse(msk);
            st.stat_ton_frames = st.stat_ton_frames + 1;
        end
    end

    % ---- 5. OM-LSA gain -----------------------------------------------------
    lam   = lam_s + lam_t + lam_tone;
    if isfield(st, 'oracle_P')                 % research: true noise PSD
        lam = max(st.oracle_P, 1e-12);
        lam_s = lam;
    end
    gamma = min(Puse ./ lam, 1e4);
    xi    = st.a_dd * st.A2prev ./ lam + (1 - st.a_dd) * max(gamma - 1, 0);
    xi    = max(xi, st.xi_min);
    v     = max(xi ./ (1 + xi) .* gamma, 1e-8);
    Glsa  = xi ./ (1 + xi) .* exp(0.5 * e1fast(v));
    ps    = 1 ./ (1 + st.qfac * (1 + xi) .* exp(-min(v, 500)));
    Gf    = st.gmin * sqrt(min(1, lam_s ./ Puse));
    G     = max(Glsa .^ ps .* Gf .^ (1 - ps), Gf);
    G     = min(G, 1);
    if p.gain_smooth
        Gs = conv(G, [0.25; 0.5; 0.25], 'same');
        Gs([1 K]) = G([1 K]);
        G = ps .* G + (1 - ps) .* Gs;      % smooth only where speech is unlikely
    end
    G = G .* st.lowcut;
    st.A2prev = G.^2 .* Puse;

    % ---- 6. synthesis -----------------------------------------------------
    S  = G .* Yuse;
    fr = real(ifft([S; conj(S(K-1:-1:2))])) .* st.win;
    st.outbuf = st.outbuf + fr;
    out = st.outbuf(1:st.R) * st.ola_norm;
    st.outbuf = [st.outbuf(st.R+1:end); zeros(st.R, 1)];
end

% ========================================================================
% src/anc/defence_anc.m
% ========================================================================
function [y, fs_out, info] = defence_anc(x, fs, p)
%DEFENCE_ANC  Hybrid adaptive noise canceller for defence communications.
%
%   [y, fs_out, info] = defence_anc(x, fs)
%   [y, fs_out, info] = defence_anc(x, fs, anc_params('name', value, ...))
%
%   x  : noisy input.  One column = single microphone.  Two columns =
%        [primary, reference] microphones (the reference picks up mostly
%        noise); an NLMS adaptive canceller then runs before the
%        single-channel stage.  Two identical columns (dual-mono file) are
%        treated as one microphone.
%   fs : input sampling rate (any; processing runs at 16 kHz)
%
%   y      : enhanced speech at fs_out = 16 kHz, time-aligned with x
%   info   : processing statistics (latency, real-time factor, ...)
%
%   Processing chain
%     (1) resample to 16 kHz, DC blocker
%     (2) optional reference-microphone NLMS adaptive noise cancellation
%     (3) frame-by-frame spectral stage (anc_process_frame):
%         SPP-MMSE stationary-noise tracker, then either
%         - AI/ML stage (default): causal GRU network that estimates the
%           speech mask from the noisy spectrum + tracked noise PSD, trained
%           on speech mixed with gunshot / machine-gun / artillery /
%           helicopter / missile / drone / siren / vehicle noise, or
%         - statistical stage (no model file): impulsive and tonal noise
%           estimators + OM-LSA optimal gain
%         and a zero-phase spectral low-cut for rumble / wind.
%   The spectral stage is causal and processes 8 ms blocks with 32 ms
%   algorithmic latency, i.e. it can run block-synchronously on a DSP /
%   embedded board (see anc_realtime_demo.m).

    if nargin < 3 || isempty(p), p = anc_params(); end
    t_start = tic;

    x = double(x);
    if isvector(x), x = x(:); end
    mode = 'single-mic';
    if size(x, 2) >= 2
        a = x(:, 1); b = x(:, 2);
        c = sum(a .* b) / sqrt(sum(a.^2) * sum(b.^2) + eps);
        if c > 0.98 && sum((a - b).^2) < 1e-3 * sum(a.^2)
            x = mean(x(:, 1:2), 2);                % dual-mono file
        else
            mode = 'dual-mic';
        end
    end

    % ---- (1) resample + high-pass ----------------------------------------
    fs_out = p.fs;
    if strcmp(mode, 'single-mic')
        xr = resample_k(x(:, 1), p.fs, fs);
    else
        xr = [resample_k(x(:, 1), p.fs, fs), resample_k(x(:, 2), p.fs, fs)];
    end
    if p.dc_block
        % y[n] = x[n] - x[n-1] + a*y[n-1]   (cut-off ~10 Hz)
        a = exp(-2 * pi * 10 / p.fs);
        xr = filter([1 -1], [1 -a], xr);
    end

    % ---- (2) reference microphone NLMS ANC ------------------------------
    if strcmp(mode, 'dual-mic')
        d = nlms_anc(xr(:, 1), xr(:, 2), p.nlms_taps, p.nlms_mu, p.nlms_vad_gate, p.fs);
    else
        d = xr(:, 1);
    end

    % ---- (3) streaming spectral stage ------------------------------------
    if p.use_dnn && ~isfield(p, 'model')
        p.model = dnn_load(p.model_file);
    end
    st = anc_init(p);
    L = numel(d);
    delay = st.N - st.R;
    nhop = ceil((L + delay) / st.R);
    din = [d; zeros(nhop * st.R - L, 1)];
    yout = zeros(nhop * st.R, 1);
    for h = 1:nhop
        idx = (h-1) * st.R + (1:st.R);
        [yout(idx), st] = anc_process_frame(din(idx), st);
    end
    y = yout(delay + 1 : delay + L);

    pk = max(abs(y));
    if pk > p.out_peak
        y = y * (p.out_peak / pk);
    end

    info.mode            = mode;
    info.fs              = p.fs;
    info.latency_ms      = st.N / p.fs * 1000;
    info.hop_ms          = st.R / p.fs * 1000;
    info.frames          = nhop;
    info.impulsive_pct   = 100 * st.stat_tr_frames / nhop;
    info.tonal_pct       = 100 * st.stat_ton_frames / nhop;
    info.proc_time_s     = toc(t_start);
    info.rtf             = info.proc_time_s / (L / p.fs);
end

% ========================================================================
% src/anc/dnn_load.m
% ========================================================================
function M = dnn_load(file)
%DNN_LOAD  Load the trained GRU mask estimator (models/defence_gru.mat).
%   M = dnn_load()        searches the usual places for defence_gru.mat
%   M = dnn_load(file)    loads a specific model file
%   Returns [] if no model is found (the canceller then falls back to the
%   purely statistical OM-LSA filter).
    M = [];
    if nargin < 1 || isempty(file)
        here = fileparts(mfilename('fullpath'));
        cand = {fullfile(here, '..', '..', 'models', 'defence_gru.mat'), ...
                fullfile(here, 'models', 'defence_gru.mat'), ...
                fullfile(pwd, 'models', 'defence_gru.mat'), ...
                which('defence_gru.mat')};
        file = '';
        for i = 1:numel(cand)
            if ~isempty(cand{i}) && exist(cand{i}, 'file')
                file = cand{i};
                break;
            end
        end
    end
    if isempty(file) || ~exist(file, 'file'), return; end
    S = load(file);
    col = @(v) double(v(:));
    M.mu  = col(S.mu);    M.sd  = col(S.sd);
    M.W1  = double(S.W1); M.b1  = col(S.b1);
    M.Wih = double(S.Wih); M.Whh = double(S.Whh);
    M.bih = col(S.bih);   M.bhh = col(S.bhh);
    M.W2  = double(S.W2); M.b2  = col(S.b2);
    M.H   = size(M.Whh, 2);
end

% ========================================================================
% src/anc/dnn_mask_step.m
% ========================================================================
function [m, h] = dnn_mask_step(P, lam_s, h, M)
%DNN_MASK_STEP  One frame of the causal GRU mask estimator (AI/ML stage).
%
%   [m, h] = dnn_mask_step(P, lam_s, h, M)
%
%   P     : |Y(k)|^2 of the current frame (257 x 1)
%   lam_s : stationary-noise PSD from the SPP-MMSE tracker (257 x 1)
%   h     : GRU state (H x 1), zeros at start-up
%   M     : network weights (struct loaded from models/defence_gru.mat)
%   m     : spectral gain / mask in [0, 1] (257 x 1)
%
%   Network: features [log P ; log lam_s] -> dense(tanh) -> GRU -> dense
%   (sigmoid).  Pure matrix algebra, so it runs in any MATLAB / Octave
%   without the Deep Learning Toolbox, and maps 1:1 to the ONNX export
%   (models/defence_gru.onnx) for Jetson / TensorRT deployment.

    f  = [log(P + 1e-10); log(lam_s + 1e-10)];
    z  = tanh(M.W1 * ((f - M.mu) ./ M.sd) + M.b1);
    H  = numel(h);
    gi = M.Wih * z + M.bih;                 % gate order: reset, update, new
    gh = M.Whh * h + M.bhh;
    r  = 1 ./ (1 + exp(-(gi(1:H) + gh(1:H))));
    u  = 1 ./ (1 + exp(-(gi(H+1:2*H) + gh(H+1:2*H))));
    n  = tanh(gi(2*H+1:3*H) + r .* gh(2*H+1:3*H));
    h  = (1 - u) .* n + u .* h;
    m  = 1 ./ (1 + exp(-(M.W2 * h + M.b2)));
end

% ========================================================================
% src/anc/e1fast.m
% ========================================================================
function e = e1fast(v)
%E1FAST  Exponential integral E1(v) for v > 0 (Abramowitz & Stegun 5.1.53/56).
%   Relative error < 6e-5; fast and toolbox-free (used by the LSA gain).
    e = zeros(size(v));
    lo = v < 1;
    x = v(lo);
    e(lo) = -log(x) - 0.57721566 + x .* (0.99999193 + x .* (-0.24991055 + ...
            x .* (0.05519968 + x .* (-0.00976004 + x * 0.00107857))));
    x = v(~lo);
    e(~lo) = exp(-x) ./ x .* (x .* x + 2.334733 * x + 0.250621) ./ ...
             (x .* x + 3.330657 * x + 1.681534);
end

% ========================================================================
% src/anc/nlms_anc.m
% ========================================================================
function [e, w] = nlms_anc(d, xref, L, mu, vad_gate, fs)
%NLMS_ANC  Two-microphone adaptive noise cancellation (Widrow ANC, NLMS).
%
%   e = nlms_anc(d, xref, L, mu, vad_gate, fs)
%
%   d        : primary microphone   (speech + noise)
%   xref     : reference microphone (noise, picked up near the source)
%   L, mu    : adaptive FIR length and normalised step size (0 < mu < 2)
%   vad_gate : true -> freeze adaptation while speech dominates the primary
%              (prevents the filter from cancelling speech that leaks into
%              the reference microphone)
%
%   e : error signal = primary minus the adaptive estimate of the noise
%       path, i.e. the speech estimate passed to the spectral stage.

    d = d(:);
    xref = xref(:);
    n = numel(d);
    w = zeros(L, 1);
    xb = zeros(L, 1);
    e = zeros(n, 1);
    delta = 1e-6 * L * max(mean(xref.^2), eps);

    % speech-activity gate from the primary / reference power ratio
    adapt = true(n, 1);
    if vad_gate
        B = round(0.016 * fs);
        nb = floor(n / B);
        Ed = sum(reshape(d(1:nb*B).^2, B, nb), 1);
        Ex = sum(reshape(xref(1:nb*B).^2, B, nb), 1) + eps;
        r = 10 * log10(Ed ./ Ex + eps);
        base = movmin(r, round(1.0 * fs / B));         % noise-only ratio
        speech = r > base + 6;
        speech = movmax(speech, 3);                    % hangover
        adapt(1:nb*B) = ~reshape(repmat(speech, B, 1), [], 1);
    end

    for k = 1:n
        xb = [xref(k); xb(1:L-1)];
        e(k) = d(k) - w' * xb;
        if adapt(k)
            w = w + (mu * e(k) / (xb' * xb + delta)) * xb;
        end
    end
end

% ========================================================================
% src/dataset/defence_noise.m
% ========================================================================
function n = defence_noise(type, dur, fs, seed)
%DEFENCE_NOISE  Synthesise defence / battlefield noise for dataset generation.
%
%   n = defence_noise(type, dur, fs)          dur in seconds
%   n = defence_noise(type, dur, fs, seed)    reproducible random seed
%
%   type (string):
%     impulsive      : 'gunshot' (single rifle shots), 'machinegun' (burst
%                      fire, ~9-12 rounds/s), 'artillery' (explosions)
%     non-stationary : 'helicopter' (blade slap + rotor harmonics),
%                      'missile' (rising turbine whine + rocket roar),
%                      'drone' (UAV rotor tones), 'siren' (wail / yelp)
%     stationary     : 'vehicle' (armoured-vehicle engine + track clatter),
%                      'hum' (100 Hz generator hum), 'wind', 'white', 'pink'
%     mixture        : 'battlefield' - machine-gun bursts + gunshots +
%                      missile whine + engine hum (like the sample
%                      recordings supplied with the problem statement)
%
%   The output is a column vector normalised to unit RMS, so it can be mixed
%   with speech at a chosen SNR (see mix_at_snr.m).  All components are
%   generated procedurally (no toolbox, no external files) and were
%   calibrated against the recordings in audio/noisy/ (e.g. the machine-gun
%   bursts are ~50-90 ms long with ~10 dB burst-to-gap modulation).

    if nargin < 4 || isempty(seed), seed = 0; end
    rng_state = rng_push(seed);
    N = round(dur * fs);
    t = (0:N-1)' / fs;

    switch lower(type)
        case 'white'
            n = randn(N, 1);
        case 'pink'
            n = pink_noise(N);
        case 'wind'
            n = wind_noise(N, fs);
        case 'hum'
            n = zeros(N, 1);
            f0 = 100 * (1 + 0.002 * randn);
            for k = 1:8
                n = n + (0.8^(k-1)) * sin(2*pi*k*f0*t + 2*pi*rand);
            end
            n = n + 0.05 * pink_noise(N) * rms(n);
        case 'gunshot'
            n = 0.02 * pink_noise(N);
            tt = poisson_times(dur, 0.9, 0.35);
            for k = 1:numel(tt)
                n = add_event(n, gunshot_event(fs, 1), tt(k), fs, db2mag(-3 + 6*rand));
            end
        case 'machinegun'
            n = machinegun(N, fs, dur);
        case 'artillery'
            n = 0.05 * brown_noise(N);
            tt = poisson_times(dur, 0.35, 1.2);
            for k = 1:numel(tt)
                n = add_event(n, explosion_event(fs), tt(k), fs, db2mag(-4 + 8*rand));
            end
        case 'helicopter'
            n = helicopter(N, fs, t);
        case 'missile'
            n = missile(N, fs, t, dur);
        case 'drone'
            n = zeros(N, 1);
            for r = 1:4
                fb = 170 + 40 * rand;
                wob = 1 + 0.01 * sin(2*pi*(0.3 + 0.5*rand)*t + 2*pi*rand);
                ph = 2*pi*cumsum(fb * wob) / fs;
                for k = 1:6
                    n = n + (0.7^k) * sin(k * ph + 2*pi*rand);
                end
            end
            n = n + 0.3 * rms(n) * pink_noise(N);
        case 'siren'
            if rand < 0.6
                T = 3.5 + rand;                                   % wail
                f = 650 + 750 * (0.5 - 0.5 * cos(2*pi*t/T));
            else
                T = 0.25 + 0.1*rand;                              % yelp
                f = 650 + 750 * mod(t / T, 1);
            end
            ph = 2*pi*cumsum(f) / fs;
            n = sin(ph) + 0.35*sin(3*ph) + 0.15*sin(5*ph);
            n = n + 0.05 * pink_noise(N);
        case 'vehicle'
            n = vehicle(N, fs, t);
        case 'battlefield'
            n = unit_rms(machinegun(N, fs, dur)) * 1.0 ...
              + unit_rms(gunshot_track(N, fs, dur)) * 0.7 ...
              + unit_rms(missile(N, fs, t, dur)) * 0.35 ...
              + unit_rms(vehicle(N, fs, t)) * 0.3;
        otherwise
            rng_pop(rng_state);
            error('defence_noise: unknown noise type ''%s''.', type);
    end
    n = unit_rms(n(:));
    rng_pop(rng_state);
end

% =========================================================================
function n = machinegun(N, fs, dur)
% Burst fire: 1-3 s bursts separated by 0.3-1 s pauses, 9-12 rounds/s.
    n = 0.01 * pink_noise(N);
    floor_env = zeros(N, 1);
    tcur = 0.1 * rand;
    while tcur < dur
        blen = 1 + 2 * rand;
        rate = 9 + 3 * rand;
        tb = tcur;
        while tb < min(tcur + blen, dur)
            n = add_event(n, gunshot_event(fs, 2), tb, fs, db2mag(-2 + 4*rand));
            tb = tb + (1 / rate) * (1 + 0.08 * randn);
        end
        i0 = max(1, round(tcur*fs) + 1);
        i1 = min(N, round(min(tcur + blen + 0.15, dur) * fs));
        floor_env(i0:i1) = 1;
        tcur = tcur + blen + 0.3 + 0.7 * rand;
    end
    % reverberant floor between rounds (about 10 dB below the bursts)
    sm = filter(1 - 0.999, [1 -0.999], floor_env);
    fl = biquad(brown_noise(N) + 0.3 * pink_noise(N), 'lp', 2500, 0.7, fs);
    n = n + 0.28 * rms(n(floor_env > 0)) * unit_rms(fl) .* sm;
end

function n = gunshot_track(N, fs, dur)
    n = zeros(N, 1);
    tt = poisson_times(dur, 0.6, 0.4);
    for k = 1:numel(tt)
        n = add_event(n, gunshot_event(fs, 1), tt(k), fs, db2mag(-3 + 6*rand));
    end
end

function e = gunshot_event(fs, kind)
% kind 1: single rifle shot (sharp crack + blast + echo)
% kind 2: machine-gun round (longer, reverberant 50-90 ms body)
    L = round(0.35 * fs);
    t = (0:L-1)' / fs;
    w = randn(L, 1);
    if kind == 1
        tau_b = 0.006 + 0.006 * rand;     % muzzle blast
        tau_d = 0.030 + 0.020 * rand;     % body
        tau_r = 0.100 + 0.080 * rand;     % reverb tail
        crack = zeros(L, 1);
        m = round(0.0008 * fs);           % supersonic N-wave (~0.8 ms)
        crack(1:2*m) = linspace(1, -1, 2*m)';
        e = 1.5 * crack + w .* exp(-t / tau_b) ...
            + 0.6 * biquad(randn(L, 1), 'lp', 900, 0.7, fs) .* exp(-t / tau_d) * 3 ...
            + 0.15 * biquad(randn(L, 1), 'lp', 2000, 0.7, fs) .* exp(-t / tau_r) * 2;
        % one discrete echo
        d = round((0.04 + 0.08 * rand) * fs);
        e(d+1:end) = e(d+1:end) + 0.3 * e(1:end-d);
    else
        tau_b = 0.012 + 0.008 * rand;
        plateau = 0.045 + 0.035 * rand;
        env = exp(-t / tau_b) + 0.35 * (t < plateau) .* exp(-t / 0.08);
        body = biquad(randn(L, 1), 'lp', 1200, 0.7, fs);
        e = 0.5 * w .* env + 1.2 * unit_rms(body) .* env * rms(w .* env) / max(rms(w .* env), eps);
        e = e + 0.2 * biquad(randn(L, 1), 'lp', 1800, 0.7, fs) .* exp(-t / 0.12);
    end
    a = round(0.0005 * fs) + 1;           % ~0.5 ms attack
    e(1:a) = e(1:a) .* linspace(0, 1, a)';
    e = biquad(e, 'hp', 60, 0.7, fs);
end

function e = explosion_event(fs)
    L = round(2.0 * fs);
    t = (0:L-1)' / fs;
    tau = 0.3 + 0.5 * rand;
    boom = biquad(brown_noise(L), 'lp', 250 + 150*rand, 0.7, fs);
    boom = unit_rms(boom) .* exp(-t / tau);
    crack = randn(L, 1) .* exp(-t / 0.015);
    rumble = biquad(randn(L, 1), 'lp', 600, 0.7, fs) .* exp(-t / (2 * tau)) * 0.3;
    e = 2.5 * boom + 0.8 * crack + rumble;
    a = round(0.002 * fs);
    e(1:a) = e(1:a) .* linspace(0, 1, a)';
end

function n = helicopter(N, fs, t)
    fb = 16 + 6 * rand;                                   % blade-pass (Hz)
    ph = 2*pi*fb*t + 2*pi*rand;
    slap = max(cos(ph), 0).^12;                           % impulsive blade slap
    broadband = biquad(pink_noise(N), 'lp', 1500, 0.7, fs);
    n = unit_rms(broadband) .* (0.4 + 1.6 * slap);
    for k = 1:10                                          % main-rotor harmonics
        n = n + 0.5 * (0.75^k) * sin(k * ph + 2*pi*rand);
    end
    ft = 5.3 * fb;                                        % tail rotor
    for k = 1:4
        n = n + 0.15 * (0.6^k) * sin(2*pi*k*ft*t + 2*pi*rand);
    end
    n = n + 0.03 * sin(2*pi*(5200 + 800*rand)*t);         % turbine whine
    n = n + 0.2 * unit_rms(biquad(randn(N, 1), 'hp', 2000, 0.7, fs)) .* (0.3 + slap);
end

function n = missile(N, fs, t, dur)
% Rising turbine / missile whine (harmonic chirp) plus rocket roar.
    f_start = 550 + 250 * rand;
    f_end = f_start * (1.8 + 0.8 * rand);
    f = f_start + (f_end - f_start) * (t / max(dur, eps));
    f = f .* (1 + 0.003 * sin(2*pi*5*t));
    ph = 2*pi*cumsum(f) / fs + 2*pi*rand;
    tone = sin(ph) + 0.6*sin(2*ph) + 0.45*sin(3*ph) + 0.2*sin(5*ph);
    roar = biquad(pink_noise(N), 'lp', 2500, 0.7, fs);
    grow = 0.6 + 0.4 * t / max(dur, eps);
    n = unit_rms(tone) + 0.7 * unit_rms(roar) .* grow;
end

function n = vehicle(N, fs, t)
    fe = 32 + 12 * rand;                                  % engine firing rate
    ph = 2*pi*fe*t + 2*pi*rand;
    n = zeros(N, 1);
    for k = 1:12
        n = n + (1 / k) * sin(k * ph + 2*pi*rand);        % sawtooth-like
    end
    n = unit_rms(n) + 0.8 * unit_rms(biquad(brown_noise(N), 'lp', 400, 0.7, fs));
    ftr = 12 + 6 * rand;                                  % track-link clatter
    clat = zeros(N, 1);
    tk = 0;
    tk = max(1,round(tk));
    while tk < length(t)
        i = round(tk * fs) + 1;
        L = min(round(0.02 * fs), N - i + 1);
        if L > 0
            tt = (0:L-1)' / fs;
            clat(i:i+L-1) = clat(i:i+L-1) + (0.5 + rand) * randn(L, 1) .* exp(-tt / 0.004);
        end
        tk = tk + (1 / ftr) * (1 + 0.1 * randn);
    end
    clat = biquad(clat, 'bp', 2500, 1.0, fs);
    n = n + 0.6 * unit_rms(clat);
    n = n + 0.3 * sin(2*pi*100*t);                        % alternator hum
end

function n = wind_noise(N, fs)
    b = biquad(brown_noise(N), 'lp', 500, 0.7, fs);
    g = filter(0.0005, [1 -0.9995], randn(N, 1));
    g = 1 + 2 * abs(g) / max(abs(g) + eps);
    n = unit_rms(b) .* g;
end

% =========================================================================
%  helpers
% =========================================================================
function n = pink_noise(N)
    b = [0.049922035 -0.095993537 0.050612699 -0.004408786];
    a = [1 -2.494956002 2.017265875 -0.522189400];
    n = filter(b, a, randn(N + 2000, 1));
    n = unit_rms(n(2001:end));
end

function n = brown_noise(N)
    n = filter(1, [1 -0.995], randn(N + 4000, 1));
    n = unit_rms(n(4001:end));
end

function y = biquad(x, type, fc, Q, fs)
% RBJ-cookbook biquad ('lp', 'hp', 'bp'), no toolbox needed.
    w0 = 2*pi*fc/fs;
    al = sin(w0) / (2*Q);
    c = cos(w0);
    switch type
        case 'lp', b = [(1-c)/2, 1-c, (1-c)/2];
        case 'hp', b = [(1+c)/2, -(1+c), (1+c)/2];
        case 'bp', b = [al, 0, -al];
    end
    a = [1+al, -2*c, 1-al];
    y = filter(b / a(1), a / a(1), x);
end

function tt = poisson_times(dur, rate, min_gap)
    tt = [];
    tc = 0.05 + (-log(rand) / rate);
    while tc < dur
        tt(end+1) = tc; %#ok<AGROW>
        tc = tc + max(min_gap, -log(rand) / rate);
    end
end

function n = add_event(n, e, t0, fs, g)
    i = round(t0 * fs) + 1;
    L = min(numel(e), numel(n) - i + 1);
    if L > 0
        n(i:i+L-1) = n(i:i+L-1) + g * e(1:L);
    end
end

function y = unit_rms(x)
    r = rms(x);
    if r > 0, y = x / r; else, y = x; end
end

function r = rms(x)
    r = sqrt(mean(x(:).^2));
end

function g = db2mag(d)
    g = 10.^(d / 20);
end

function s = rng_push(seed)
    s = rng();
    rng(seed);
end

function rng_pop(s)
    rng(s);
end

% ========================================================================
% src/dataset/make_dataset.m
% ========================================================================
function make_dataset(clean_dir, out_dir, n_pairs, snr_range, noise_types)
%MAKE_DATASET  Scalable noisy / clean speech pair generator.
%
%   make_dataset('audio/clean', 'dataset', 200)
%   make_dataset(clean_dir, out_dir, n_pairs, [-10 20], {'machinegun','gunshot'})
%
%   For every pair a random clean utterance is mixed with a random defence
%   noise (defence_noise.m) at a random SNR drawn from snr_range (dB), with
%   augmentation: random level, reverberation (synthetic room impulse
%   response) and occasional clipping.  Writes
%       out_dir/clean/pair_00001.wav   out_dir/noisy/pair_00001.wav
%       out_dir/manifest.csv           (file, speech, noise, snr, reverb, clip)
    if nargin < 3, n_pairs = 100; end
    if nargin < 4, snr_range = [-10 20]; end
    if nargin < 5
        noise_types = {'gunshot', 'machinegun', 'artillery', 'helicopter', ...
            'missile', 'drone', 'siren', 'vehicle', 'hum', 'wind', 'battlefield'};
    end
    fs = 16000;
    files = dir(fullfile(clean_dir, '*.wav'));
    if isempty(files), error('make_dataset: no .wav files in %s', clean_dir); end
    if ~exist(fullfile(out_dir, 'clean'), 'dir'), mkdir(fullfile(out_dir, 'clean')); end
    if ~exist(fullfile(out_dir, 'noisy'), 'dir'), mkdir(fullfile(out_dir, 'noisy')); end
    fid = fopen(fullfile(out_dir, 'manifest.csv'), 'w');
    fprintf(fid, 'file,speech,noise,snr_db,reverb_t60,clipped\n');
    for i = 1:n_pairs
        f = files(randi(numel(files)));
        [s, fs0] = audioread(fullfile(clean_dir, f.name));
        s = resample_k(mean(s, 2), fs, fs0);
        s = s / max(abs(s) + eps) * 0.5;
        t60 = 0;
        if rand < 0.3                                   % reverberation
            t60 = 0.2 + 0.5 * rand;
            L = round(t60 * fs);
            h = randn(L, 1) .* exp(-6.9 * (0:L-1)' / L);
            h(1) = 3;
            s = filter(h / norm(h), 1, s);
        end
        nt = noise_types{randi(numel(noise_types))};
        snr = snr_range(1) + diff(snr_range) * rand;
        n = defence_noise(nt, numel(s) / fs, fs, 500000 + i);
        noisy = mix_at_snr(s, n, snr);
        g = 10^((-20 + 14 * rand) / 20) / max(abs(noisy));   % random level
        noisy = noisy * g;  s = s * g;
        clipped = rand < 0.05;
        if clipped
            noisy = max(min(noisy, 0.7 * max(abs(noisy))), -0.7 * max(abs(noisy)));
        end
        name = sprintf('pair_%05d.wav', i);
        audiowrite(fullfile(out_dir, 'clean', name), s, fs);
        audiowrite(fullfile(out_dir, 'noisy', name), noisy, fs);
        fprintf(fid, '%s,%s,%s,%.2f,%.2f,%d\n', name, f.name, nt, snr, t60, clipped);
    end
    fclose(fid);
    fprintf('%d noisy/clean pairs written to %s\n', n_pairs, out_dir);
end

% ========================================================================
% src/dataset/make_noise_bank.m
% ========================================================================
function make_noise_bank(out_dir, clips_per_type, clip_s, seed0)
%MAKE_NOISE_BANK  Write a bank of synthetic defence-noise clips (training data).
%
%   make_noise_bank('noisebank', 60, 12)   -> 11 types x 60 clips x 12 s
%
%   Used to train the GRU mask estimator (tools/train_dnn.py).  Seeds start
%   at seed0 (default 100000) so they never overlap with the evaluation
%   noise used in main_defence_anc.m.
    if nargin < 2, clips_per_type = 60; end
    if nargin < 3, clip_s = 12; end
    if nargin < 4, seed0 = 100000; end
    types = {'gunshot', 'machinegun', 'artillery', 'helicopter', 'missile', ...
             'drone', 'siren', 'vehicle', 'hum', 'wind', 'battlefield'};
    fs = 16000;
    if ~exist(out_dir, 'dir'), mkdir(out_dir); end
    for i = 1:numel(types)
        for k = 1:clips_per_type
            n = defence_noise(types{i}, clip_s, fs, seed0 + 1000 * i + k);
            n = 0.99 * n / max(abs(n));
            audiowrite(fullfile(out_dir, sprintf('%s_%03d.wav', types{i}, k)), n, fs);
        end
        fprintf('%-12s %d clips\n', types{i}, clips_per_type);
    end
end

% ========================================================================
% src/dataset/mix_at_snr.m
% ========================================================================
function [noisy, noise_scaled, g] = mix_at_snr(clean, noise, snr_db)
%MIX_AT_SNR  Add noise to clean speech at a prescribed global SNR (dB).
%
%   [noisy, noise_scaled, g] = mix_at_snr(clean, noise, snr_db)
%
%   The noise is looped/cropped to the length of the clean signal and scaled
%   by g so that 10*log10(sum(clean.^2) / sum(noise_scaled.^2)) = snr_db.

    clean = clean(:);
    noise = noise(:);
    N = numel(clean);
    if numel(noise) < N
        noise = repmat(noise, ceil(N / numel(noise)), 1);
    end
    noise = noise(1:N);
    ps = sum(clean.^2);
    pn = sum(noise.^2);
    g = sqrt(ps / (pn * 10^(snr_db / 10)));
    noise_scaled = g * noise;
    noisy = clean + noise_scaled;
end

% ========================================================================
% src/metrics/blind_snr.m
% ========================================================================
function r = blind_snr(noisy, enhanced, fs)
%BLIND_SNR  No-reference SNR estimate for real recordings.
%
%   r = blind_snr(noisy, enhanced, fs)      (both time-aligned, same fs)
%
%   True SNR / STOI / PESQ need the clean speech, which does not exist for a
%   real battlefield recording.  This function gives the usual practical
%   substitute: frames are classified as speech / non-speech with an energy
%   VAD run on the (much cleaner) enhanced signal, and for each signal
%       SNR_est = 10 log10( (P_speech_frames - P_noise_frames) / P_noise_frames )
%   r.snr_in, r.snr_out : estimated SNR before / after (dB)
%   r.noise_reduction   : attenuation of the background in speech pauses (dB)
%   r.speech_frames     : fraction of frames classified as speech
    x = noisy(:);
    y = enhanced(:);
    n = min(numel(x), numel(y));
    x = x(1:n); y = y(1:n);
    N = round(0.032 * fs);
    nf = floor(n / N);
    Ex = mean(reshape(x(1:nf*N), N, nf).^2, 1)';
    Ey = mean(reshape(y(1:nf*N), N, nf).^2, 1)';
    Eys = sort(Ey);
    floor_y = mean(Eys(1:max(1, round(0.1 * nf))));        % quietest 10 %
    sp = Ey > max(floor_y, eps) * 10^(15/10);                % 15 dB above floor
    sp = logical(conv(double(sp), ones(3, 1), 'same'));      % hangover
    if ~any(sp) || all(sp)
        r = struct('snr_in', NaN, 'snr_out', NaN, 'noise_reduction', NaN, ...
                   'speech_frames', mean(sp));
        return;
    end
    est = @(E) 10 * log10(max(mean(E(sp)) - mean(E(~sp)), 1e-3 * mean(E(~sp))) / mean(E(~sp)));
    r.snr_in = est(Ex);
    r.snr_out = est(Ey);
    r.noise_reduction = 10 * log10(mean(Ex(~sp)) / max(mean(Ey(~sp)), eps));
    r.speech_frames = mean(sp);
end

% ========================================================================
% src/metrics/evaluate_pair.m
% ========================================================================
function r = evaluate_pair(clean, test, fs)
%EVALUATE_PAIR  [SNR (dB), STOI, PESQ-WB (P.862.2), PESQ-NB (P.862.1)] of test vs clean.
    m = snr_metrics(clean, test, fs);
    r = [m.snr, stoi_score(clean, test, fs), pesq_score(clean, test, fs, 'wb'), ...
         pesq_score(clean, test, fs, 'nb')];
end

% ========================================================================
% src/metrics/pesq_score.m
% ========================================================================
function [mos, raw] = pesq_score(ref, deg, fs, mode)
%PESQ_SCORE  Perceptual Evaluation of Speech Quality (ITU-T P.862 family).
%
%   mos = pesq_score(ref, deg, fs)         wide-band  PESQ, P.862.2 MOS-LQO
%   mos = pesq_score(ref, deg, fs, 'nb')   narrow-band PESQ, P.862 + P.862.1 MOS-LQO
%   [mos, raw] = pesq_score(...)           raw = P.862 raw score (NB only)
%
%   ref : clean reference speech          deg : degraded / enhanced speech
%   fs  : sampling rate.  'wb' works at 16 kHz, 'nb' at 8 or 16 kHz; any
%         other rate is resampled automatically (16 kHz for wb, 8 kHz nb).
%
%   Score range: about -0.5 ... 4.5 (MOS-LQO about 1.0 ... 4.64); higher is
%   better.  The signals do not need to be time aligned - PESQ performs its
%   own level alignment, IRS / wide-band input filtering, utterance-based
%   time-delay estimation and bad-interval re-alignment.
%
%   Independent, toolbox-free MATLAB re-implementation of the algorithm
%   specified in ITU-T Recommendations P.862 (2001), P.862.1 (2003) and
%   P.862.2 (2005).  Its output was cross-checked against the ITU-T ANSI-C
%   reference implementation (see tools/validate_metrics.py).
%
%   IPR NOTICE: the PESQ algorithm is the intellectual property of OPTICOM
%   GmbH and Psytechnics Ltd.  This implementation is provided for research
%   and educational use only (e.g. evaluating an enhancement algorithm in
%   an academic project).  Any commercial use requires a PESQ licence from
%   the IPR owners; for certified results use the ITU-T reference software.

    if nargin < 4 || isempty(mode), mode = 'wb'; end
    mode = lower(mode);
    ref = double(ref(:));
    deg = double(deg(:));
    if strcmp(mode, 'wb')
        if fs ~= 16000
            ref = resample_k(ref, 16000, fs);
            deg = resample_k(deg, 16000, fs);
            fs  = 16000;
        end
    elseif strcmp(mode, 'nb')
        if fs ~= 8000 && fs ~= 16000
            ref = resample_k(ref, 8000, fs);
            deg = resample_k(deg, 8000, fs);
            fs  = 8000;
        end
    else
        error('pesq_score: mode must be ''wb'' or ''nb''.');
    end

    % Scale as the reference wrapper does (the score is level independent).
    mx = max(max(abs(ref)), max(abs(deg)));
    if mx > 0
        ref = ref / mx;
        deg = deg / mx;
    end

    C = pesq_constants(fs, mode);
    raw = NaN;
    mos = NaN;

    r = load_src(ref, C);
    d = load_src(deg, C);
    if (r.Nsamples - 2*C.SB*C.DS < fs/4) || (d.Nsamples - 2*C.SB*C.DS < fs/4)
        warning('pesq_score:short', 'Signals shorter than 0.25 s - PESQ not computed.');
        return;
    end

    maxN = max(r.Nsamples, d.Nsamples);
    r = fix_power_level(r, maxN, C);
    d = fix_power_level(d, maxN, C);

    if strcmp(mode, 'nb')
        r.data = apply_filter(r.data, r.Nsamples, C.IRS_dB, C);
        d.data = apply_filter(d.data, d.Nsamples, C.IRS_dB, C);
    else
        r.data = wb_input_filter(r.data, r.Nsamples, C);
        d.data = wb_input_filter(d.data, d.Nsamples, C);
    end

    model_ref = r.data;
    model_deg = d.data;

    % ---- time alignment (operates on a band-filtered copy) --------------
    r.data = dc_block(r.data, r.Nsamples, C);
    d.data = dc_block(d.data, d.Nsamples, C);
    r.data = sos_filter(C.InIIR, r.data);
    d.data = sos_filter(C.InIIR, d.data);
    [r.VAD, r.logVAD] = apply_vad(r.data, r.Nsamples, C);
    [d.VAD, d.logVAD] = apply_vad(d.data, d.Nsamples, C);

    E = struct();
    E.Crude_DelayEst = crude_delay(r.logVAD, fix(r.Nsamples/C.DS), 0, ...
                                   d.logVAD, fix(d.Nsamples/C.DS), 0) * C.DS;
    E = utterance_locate(r, d, E, C);
    if E.Nutterances < 1
        warning('pesq_score:noutt', 'No utterances detected - PESQ not computed.');
        return;
    end

    % ---- perceptual model on the level-aligned, input-filtered signals ---
    r.data = model_ref;
    d.data = model_deg;
    if numel(r.data) < numel(d.data)
        r.data(end+1:numel(d.data)) = 0;
    elseif numel(d.data) < numel(r.data)
        d.data(end+1:numel(r.data)) = 0;
    end
    raw = psychoacoustic_model(r, d, E, C);

    if strcmp(mode, 'nb')
        mos = 0.999 + 4 / (1 + exp(-1.4945 * raw + 4.6607));
    else
        mos = 0.999 + 4 / (1 + exp(-1.3669 * raw + 3.8224));
        raw = NaN;
    end
end

% =========================================================================
%  Constants and tables (ITU-T P.862 / P.862.2)
% =========================================================================
function C = pesq_constants(fs, mode)
    C.Fs   = fs;
    C.mode = mode;
    C.SB   = 75;                    % SEARCHBUFFER (VAD windows)
    C.DPAD = 320 * (fs / 1000);     % DATAPADDING_MSECS
    C.MINSPEECHLGTH  = 4;
    C.JOINSPEECHLGTH = 50;
    C.MINUTTLENGTH   = 50;
    C.MAXNUTT        = 50;

    C.align_dB = [0 -500; 50 -500; 100 -500; 125 -500; 160 -500; 200 -500; ...
        250 -500; 300 -500; 350 0; 400 0; 500 0; 600 0; 630 0; 800 0; 1000 0; ...
        1250 0; 1600 0; 2000 0; 2500 0; 3000 0; 3250 0; 3500 -500; 4000 -500; ...
        5000 -500; 6300 -500; 8000 -500];
    C.IRS_dB = [0 -200; 50 -40; 100 -20; 125 -12; 160 -6; 200 0; 250 4; ...
        300 6; 350 8; 400 10; 500 11; 600 12; 700 12; 800 12; 1000 12; ...
        1300 12; 1600 12; 2000 12; 2500 12; 3000 12; 3250 12; 3500 4; ...
        4000 -200; 5000 -200; 6300 -200; 8000 -200];

    abs_thresh = [51286152.000000 2454709.500000 70794.593750 4897.788574 ...
        1174.897705 389.045166 104.712860 45.708820 17.782795 9.772372 ...
        4.897789 3.090296 1.905461 1.258925 0.977237 0.724436 0.562341 ...
        0.457088 0.389045 0.331131 0.295121 0.269153 0.257040 0.251189 ...
        0.251189 0.251189 0.251189 0.263027 0.288403 0.309030 0.338844 ...
        0.371535 0.398107 0.436516 0.467735 0.489779 0.501187 0.501187 ...
        0.512861 0.524807 0.524807 0.524807 0.512861 0.478630 0.426580 ...
        0.371535 0.363078 0.416869 0.537032];
    bark_centre = [0.078672 0.316341 0.636559 0.961246 1.290450 1.624217 ...
        1.962597 2.305636 2.653383 3.005889 3.363201 3.725371 4.092449 ...
        4.464486 4.841533 5.223642 5.610866 6.003256 6.400869 6.803755 ...
        7.211971 7.625571 8.044611 8.469146 8.899232 9.334927 9.776288 ...
        10.223374 10.676242 11.134952 11.599563 12.070135 12.546731 ...
        13.029408 13.518232 14.013264 14.514566 15.022202 15.536238 ...
        16.056736 16.583761 17.117382 17.657663 18.204674 18.758478 ...
        19.319147 19.886751 20.461355 21.043034];
    bark_width = [0.157344 0.317994 0.322441 0.326934 0.331474 0.336061 ...
        0.340697 0.345381 0.350114 0.354897 0.359729 0.364611 0.369544 ...
        0.374529 0.379565 0.384653 0.389794 0.394989 0.400236 0.405538 ...
        0.410894 0.416306 0.421773 0.427297 0.432877 0.438514 0.444209 ...
        0.449962 0.455774 0.461645 0.467577 0.473569 0.479621 0.485736 ...
        0.491912 0.498151 0.504454 0.510819 0.517250 0.523745 0.530308 ...
        0.536934 0.543629 0.550390 0.557220 0.564119 0.571085 0.578125 ...
        0.585232];
    pdc = [100.000000 99.999992 100.000000 100.000008 100.000008 100.000015 ...
        99.999992 99.999969 50.000027 100.000000 99.999969 100.000015 ...
        99.999947 100.000061 53.047077 110.000046 117.991989 65.000000 ...
        68.760147 69.999931 71.428818 75.000038 76.843384 80.968781 ...
        88.646126 63.864388 68.155350 72.547775 75.584831 58.379192 ...
        80.950836 64.135651 54.384785 73.821884 64.437073 59.176456 ...
        65.521278 61.399822 58.144047 57.004543 64.126297];
    nbands = [1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 2 2 2 2 2 2 2 2 3 3 3 3 4 ...
        3 4 5 4 5 6 6 7 8 9 9];

    if fs == 16000
        C.DS = 64;  C.AlignNfft = 1024;
        C.Nb = 49;  C.Sl = 1.866055e-1;  C.Sp = 6.910853e-6;
        C.nbands = [nbands 12 12 15 16 18 21 25 20];
        C.pdc    = [pdc 54.311001 61.114979 55.077751 56.849335 55.628868 ...
                    53.137054 54.985844 79.546974];
        C.InIIR = [0.325631521 -0.086782860 -0.238848661 -1.079416490 0.434583902; ...
                   0.403961804 -0.556985881  0.153024077 -0.415115835 0.696590244; ...
                   4.736162769  3.287251046  1.753289019 -1.859599046 0.876284034; ...
                   0.365373469  0.000000000  0.000000000 -0.634626531 0.000000000; ...
                   0.884811506  0.000000000  0.000000000 -0.256725271 0.141536777; ...
                   0.723593055 -1.447186099  0.723593044 -1.129587469 0.657232737; ...
                   1.644910855 -1.817280902  1.249658063 -1.778403899 0.801724355; ...
                   0.633692689 -0.284644314 -0.319789663  0.000000000 0.000000000; ...
                   1.032763031  0.268428979  0.602913323  0.000000000 0.000000000; ...
                   1.001616361 -0.823749013  0.439731942 -0.885778255 0.000000000; ...
                   0.752472096 -0.375388990  0.188977609 -0.077258216 0.247230734; ...
                   1.023700575  0.001661628  0.521284240 -0.183867259 0.354324187];
        C.WBIIR = [2.740826 -5.4816519 2.740826 -1.9444777 0.94597794];
        C.abs_thresh  = abs_thresh(1:49);
        C.bark_centre = bark_centre(1:49);
        C.bark_width  = bark_width(1:49);
        C.pdc = C.pdc(1:49);
    elseif fs == 8000
        C.DS = 32;  C.AlignNfft = 512;
        C.Nb = 42;  C.Sl = 1.866055e-1;  C.Sp = 2.764344e-5;
        C.nbands = [nbands 11];
        C.pdc    = [pdc 59.248363];
        C.InIIR = [0.885535424 -0.885535424  0.000000000 -0.771070709 0.000000000; ...
                   0.895092588  1.292907193  0.449260174  1.268869037 0.442025372; ...
                   4.049527940 -7.865190042  3.815662102 -1.746859852 0.786305963; ...
                   0.500002353 -0.500002353  0.000000000  0.000000000 0.000000000; ...
                   0.565002834 -0.241585934 -0.306009671  0.259688659 0.249979657; ...
                   2.115237288  0.919935084  1.141240051 -1.587313419 0.665935315; ...
                   0.912224584 -0.224397719 -0.641121413 -0.246029464 -0.556720590; ...
                   0.444617727 -0.307589321  0.141638062 -0.996391149 0.502251622];
        C.WBIIR = [2.6657628 -5.3315255 2.6657628 -1.8890331 0.89487434];
        C.abs_thresh  = abs_thresh(1:42);
        C.bark_centre = bark_centre(1:42);
        C.bark_width  = bark_width(1:42);
    else
        error('pesq_score: fs must be 8000 or 16000.');
    end
    C.Nf = 8 * C.DS;                % psychoacoustic frame length
    % Hz-bin -> Bark-band summation matrix (includes power density correction)
    C.W = zeros(C.Nb, C.Nf/2);
    k = 0;
    for b = 1:C.Nb
        C.W(b, k+1:k+C.nbands(b)) = C.pdc(b) * C.Sp;
        k = k + C.nbands(b);
    end
end

% =========================================================================
%  Pre-processing
% =========================================================================
function s = load_src(x, C)
    pad = C.SB * C.DS;
    s.Nsamples = numel(x) + 2 * pad;
    s.data = [zeros(pad, 1); x; zeros(C.DPAD + pad, 1)];
end

function p = nextpow2_c(x)
    p = 1;
    while p < x
        p = p * 2;
    end
end

function y = real_ifft_half(Xh, P)
    y = real(ifft([Xh; conj(Xh(P/2:-1:2))]));
end

function data = apply_filter(data, nsamp, curve, C)
% FFT-domain filtering with a piecewise-linear dB magnitude curve.
    ofs = C.SB * C.DS;
    n = nsamp - 2 * ofs + C.DPAD;
    P = nextpow2_c(n);
    x = zeros(P, 1);
    x(1:n) = data(ofs+1:ofs+n);
    X = fft(x);
    f = (0:P/2)' * (C.Fs / P);
    g = interp1(curve(:,1), curve(:,2), f, 'linear', 'extrap') ...
        - interp1(curve(:,1), curve(:,2), 1000, 'linear', 'extrap');
    Xh = X(1:P/2+1) .* 10.^(g / 20);
    y = real_ifft_half(Xh, P);
    data(ofs+1:ofs+n) = y(1:n);
end

function s = fix_power_level(s, maxN, C)
    ofs = C.SB * C.DS;
    af = apply_filter(s.data, s.Nsamples, C.align_dB, C);
    pw = sum(af(ofs+1 : s.Nsamples - ofs + C.DPAD).^2) / (maxN - 2*ofs + C.DPAD);
    g = sqrt(1e7 / pw);
    s.data(1:s.Nsamples) = s.data(1:s.Nsamples) * g;
end

function data = wb_input_filter(data, nsamp, C)
    ofs = C.SB * C.DS;
    for i = 0:15
        data(ofs + i) = data(ofs + i) * i / 16;               % C: ofs+i-1
        data(nsamp - ofs - i + 1) = data(nsamp - ofs - i + 1) * i / 16;
    end
    idx = ofs+1 : nsamp - ofs;
    data(idx) = sos_filter(C.WBIIR, data(idx));
end

function y = sos_filter(H, x)
    y = x;
    for k = 1:size(H, 1)
        y = filter(H(k, 1:3), [1 H(k, 4:5)], y);
    end
end

function data = dc_block(data, nsamp, C)
    ofs = C.SB * C.DS;
    idx = ofs+1 : nsamp - ofs;
    data(idx) = data(idx) - sum(data(idx)) / nsamp;
    for c = 0:C.DS-1
        data(ofs + c + 1) = data(ofs + c + 1) * (0.5 + c) / C.DS;
    end
    for c = 0:C.DS-1
        data(nsamp - ofs - c) = data(nsamp - ofs - c) * (0.5 + c) / C.DS;
    end
end

function [VAD, logVAD] = apply_vad(data, nsamp, C)
% Energy-based voice activity detector of P.862 (4 ms windows).
    Nw  = fix(nsamp / C.DS);
    VAD = mean(reshape(data(1:Nw*C.DS).^2, C.DS, Nw), 1)';
    LevelThresh = mean(VAD);
    LevelMin = max(VAD);
    if LevelMin > 0, LevelMin = LevelMin * 1e-4; else, LevelMin = 1; end
    VAD(VAD < LevelMin) = LevelMin;
    for it = 1:12
        sel = VAD <= LevelThresh;
        LevelNoise = 0; StDNoise = 0;
        if any(sel)
            LevelNoise = mean(VAD(sel));
            StDNoise = sqrt(mean((VAD(sel) - LevelNoise).^2));
        end
        LevelThresh = 1.001 * (LevelNoise + 2 * StDNoise);
    end
    sp = VAD > LevelThresh;
    if any(sp), LevelSig = mean(VAD(sp)); else, LevelSig = 0; LevelThresh = -1; end
    if any(~sp), LevelNoise = mean(VAD(~sp)); else, LevelNoise = 1; end
    VAD(VAD <= LevelThresh) = -VAD(VAD <= LevelThresh);
    VAD(1)  = -LevelMin;
    VAD(Nw) = -LevelMin;

    % remove very short speech bursts
    start = 0;
    for c = 1:Nw-1                                   % C index c
        if VAD(c+1) > 0 && VAD(c) <= 0, start = c; end
        if VAD(c+1) <= 0 && VAD(c) > 0
            finish = c;
            if finish - start <= C.MINSPEECHLGTH
                VAD(start+1:finish) = -VAD(start+1:finish);
            end
        end
    end
    % remove low-energy bursts if the signal is very clean
    if LevelSig >= LevelNoise * 1000
        start = 0;
        for c = 1:Nw-1
            if VAD(c+1) > 0 && VAD(c) <= 0, start = c; end
            if VAD(c+1) <= 0 && VAD(c) > 0
                finish = c;
                g = sum(VAD(start+1:finish));
                if g < 3 * LevelThresh * (finish - start)
                    VAD(start+1:finish) = -VAD(start+1:finish);
                end
            end
        end
    end
    % join speech segments separated by short pauses
    start = 0; finish = 0;
    for c = 1:Nw-1
        if VAD(c+1) > 0 && VAD(c) <= 0
            start = c;
            if finish > 0 && (start - finish) <= C.JOINSPEECHLGTH
                VAD(finish+1:start) = LevelMin;
            end
        end
        if VAD(c+1) <= 0 && VAD(c) > 0, finish = c; end
    end
    start = 0;
    for c = 1:Nw-1
        if VAD(c+1) > 0 && VAD(c) <= 0, start = c; end
    end
    if start == 0
        VAD = abs(VAD);
        VAD(1) = -LevelMin;
        VAD(Nw) = -LevelMin;
    end
    % soften onsets / offsets
    c = 3;
    while c < Nw - 2
        if VAD(c+1) > 0 && VAD(c-1) <= 0
            VAD(c-1) = VAD(c+1) * 0.1;
            VAD(c)   = VAD(c+1) * 0.3;
            c = c + 1;
        end
        if VAD(c+1) <= 0 && VAD(c) > 0
            VAD(c+1) = VAD(c) * 0.3;
            VAD(c+2) = VAD(c) * 0.1;
            c = c + 3;
        end
        c = c + 1;
    end
    VAD(VAD < 0) = 0;
    if LevelThresh <= 0, LevelThresh = LevelMin; end
    logVAD = zeros(Nw, 1);
    act = VAD > LevelThresh;
    logVAD(act) = log(VAD(act) / LevelThresh);
end

% =========================================================================
%  Time alignment
% =========================================================================
function dly = crude_delay(rv, nr, sr, dv, nd, sd)
% Envelope cross-correlation (logVAD) -> delay in VAD windows.
    Imax = nr - 1;
    if nr > 1 && nd > 1
        Y = conv(flipud(rv(sr+1:sr+nr)), dv(sd+1:sd+nd));
        m = 0;
        for c = 0:nr+nd-2
            if Y(c+1) > m
                m = Y(c+1);
                Imax = c;
            end
        end
    end
    dly = Imax - nr + 1;
end

function E = crude_align_utt(r, d, E, uid, C)
    startr = E.UttSearch_Start(uid);
    startd = startr + fix(E.Crude_DelayEst / C.DS);
    if startd < 0
        startr = -fix(E.Crude_DelayEst / C.DS);
        startd = 0;
    end
    nr = E.UttSearch_End(uid) - startr;
    nd = nr;
    if startd + nd > fix(d.Nsamples / C.DS)
        nd = fix(d.Nsamples / C.DS) - startd;
    end
    E.Utt_DelayEst(uid) = crude_delay(r.logVAD, nr, startr, d.logVAD, nd, startd) ...
                          * C.DS + E.Crude_DelayEst;
end

function dly = crude_align_test(r, d, estdelay, sstart, send, C)
% crude_align() with Utt_id == MAXNUTTERANCES (used by split_align).
    startr = sstart;
    startd = startr + fix(estdelay / C.DS);
    if startd < 0
        startr = -fix(estdelay / C.DS);
        startd = 0;
    end
    nr = send - startr;
    nd = nr;
    if startd + nd > fix(d.Nsamples / C.DS)
        nd = fix(d.Nsamples / C.DS) - startd;
    end
    dly = crude_delay(r.logVAD, nr, startr, d.logVAD, nd, startd) * C.DS + estdelay;
end

function w = hann_periodic(N)
    w = 0.5 * (1 - cos(2 * pi * (0:N-1)' / N));
end

function [pk, wt] = xcorr_peaks(r, d, starts_r, starts_d, C)
% For each frame pair: indicator of lags within 99 % of the max |xcorr|
% and the frame weight (0.99*max)^0.125.
    N = C.AlignNfft;
    nf = numel(starts_r);
    pk = false(N, nf);
    wt = zeros(1, nf);
    if nf == 0, return; end
    w = hann_periodic(N);
    idx = (0:N-1)';
    X1 = fft(r.data(idx + starts_r(:)' + 1) .* repmat(w, 1, nf));
    X2 = fft(d.data(idx + starts_d(:)' + 1) .* repmat(w, 1, nf));
    xc = abs(real(ifft(conj(X1) .* X2)));
    vmax = 0.99 * max(xc, [], 1);
    pk = xc > repmat(vmax, N, 1);
    wt = vmax .^ 0.125;
end

function h = circ_tri_smooth(v, kernel)
% circular convolution with triangle 1 - |k|/kernel, |k| < kernel
    h = v;
    for k = 1:kernel-1
        h = h + (1 - k/kernel) * (circshift(v, k) + circshift(v, -k));
    end
end

function E = time_align(r, d, E, uid, C)
    N = C.AlignNfft;
    estdelay = E.Utt_DelayEst(uid);
    startr = E.UttSearch_Start(uid) * C.DS;
    startd = startr + estdelay;
    if startd < 0
        startr = -estdelay;
        startd = 0;
    end
    nf = 0;
    while (startd + (nf)*N/4 + N <= d.Nsamples) && ...
          (startr + (nf)*N/4 + N <= E.UttSearch_End(uid) * C.DS)
        nf = nf + 1;
    end
    sr = startr + (0:nf-1) * N/4;
    sd = startd + (0:nf-1) * N/4;
    [pk, wt] = xcorr_peaks(r, d, sr, sd, C);
    H = double(pk) * wt(:);
    Hsum = sum(H);
    H = abs(circ_tri_smooth(H, N/64));
    if Hsum > 0, H = H / Hsum; else, H = zeros(N, 1); end
    [vmax, I] = max(H);
    Imax = I - 1;
    if vmax <= 0, Imax = 0; vmax = 0; end
    if Imax >= N/2, Imax = Imax - N; end
    E.Utt_Delay(uid) = estdelay + Imax;
    E.Utt_DelayConf(uid) = vmax;
end

function E = id_searchwindows(r, d, E, C)
    VL = fix(r.Nsamples / C.DS);
    dstart = C.MINUTTLENGTH - fix(E.Crude_DelayEst / C.DS);
    dend = fix((d.Nsamples - E.Crude_DelayEst) / C.DS) - C.MINUTTLENGTH;
    n = 0; flag = 0; this_start = 0;
    E.UttSearch_Start = zeros(1, C.MAXNUTT);
    E.UttSearch_End = zeros(1, C.MAXNUTT);
    for c = 0:VL-1
        v = r.VAD(c+1);
        if v > 0 && flag == 0
            flag = 1;
            this_start = c;
            E.UttSearch_Start(n+1) = max(c - C.SB, 0);
        end
        if (v == 0 || c == VL-1) && flag == 1
            flag = 0;
            E.UttSearch_End(n+1) = min(c + C.SB, VL - 1);
            if (c - this_start) >= C.MINUTTLENGTH && this_start < dend && c > dstart
                n = n + 1;
            end
        end
    end
    E.Nutterances = n;
end

function E = id_utterances(r, d, E, C)
    VL = fix(r.Nsamples / C.DS);
    dstart = C.MINUTTLENGTH - fix(E.Crude_DelayEst / C.DS);
    dend = fix((d.Nsamples - E.Crude_DelayEst) / C.DS) - C.MINUTTLENGTH;
    n = 0; flag = 0; this_start = 0;
    for c = 0:VL-1
        v = r.VAD(c+1);
        if v > 0 && flag == 0
            flag = 1;
            this_start = c;
            E.Utt_Start(n+1) = c;
        end
        if (v == 0 || c == VL-1) && flag == 1
            flag = 0;
            E.Utt_End(n+1) = c;
            if (c - this_start) >= C.MINUTTLENGTH && this_start < dend && c > dstart
                n = n + 1;
            end
        end
    end
    Nu = E.Nutterances;
    E.Utt_Start(1) = C.SB;
    E.Utt_End(Nu) = VL - C.SB;
    for u = 2:Nu
        c = fix((E.Utt_Start(u) + E.Utt_End(u-1)) / 2);
        E.Utt_Start(u) = c;
        E.Utt_End(u-1) = c;
    end
    this_start = E.Utt_Start(1) * C.DS + E.Utt_Delay(1);
    if this_start < C.SB * C.DS
        E.Utt_Start(1) = C.SB + fix((C.DS - 1 - E.Utt_Delay(1)) / C.DS);
    end
    last_end = E.Utt_End(Nu) * C.DS + E.Utt_Delay(Nu);
    if last_end > d.Nsamples - C.SB * C.DS
        E.Utt_End(Nu) = fix((d.Nsamples - E.Utt_Delay(Nu)) / C.DS) - C.SB;
    end
    for u = 2:Nu
        this_start = E.Utt_Start(u) * C.DS + E.Utt_Delay(u);
        last_end = E.Utt_End(u-1) * C.DS + E.Utt_Delay(u-1);
        if this_start < last_end
            c = fix((this_start + last_end) / 2);
            E.Utt_Start(u) = fix((C.DS - 1 + c - E.Utt_Delay(u)) / C.DS);
            E.Utt_End(u-1) = fix((c - E.Utt_Delay(u-1)) / C.DS);
        end
    end
end

function E = utterance_locate(r, d, E, C)
    E = id_searchwindows(r, d, E, C);
    Z = zeros(1, C.MAXNUTT);
    E.Utt_DelayEst = Z; E.Utt_Delay = Z; E.Utt_DelayConf = Z;
    E.Utt_Start = Z; E.Utt_End = Z;
    for u = 1:E.Nutterances
        E = crude_align_utt(r, d, E, u, C);
        E = time_align(r, d, E, u, C);
    end
    if E.Nutterances < 1, return; end
    E = id_utterances(r, d, E, C);
    E = utterance_split(r, d, E, C);
end

function E = utterance_split(r, d, E, C)
    u = 1;
    while u <= E.Nutterances && E.Nutterances < C.MAXNUTT
        dEst  = E.Utt_DelayEst(u);
        dConf = E.Utt_DelayConf(u);
        uS = E.Utt_Start(u);
        uE = E.Utt_End(u);
        sS = uS;
        while sS < uE && r.VAD(sS+1) <= 0, sS = sS + 1; end
        sE = uE;
        while sE > uS && r.VAD(sE+1) <= 0, sE = sE - 1; end
        sE = sE + 1;
        if (sE - sS) >= 200
            [ED1, D1, DC1, ED2, D2, DC2, BP] = split_align(r, d, uS, sS, sE, uE, ...
                                                           dEst, dConf, C);
            if DC1 > dConf && DC2 > dConf
                for st = E.Nutterances:-1:u+1
                    E.Utt_DelayEst(st+1)  = E.Utt_DelayEst(st);
                    E.Utt_Delay(st+1)     = E.Utt_Delay(st);
                    E.Utt_DelayConf(st+1) = E.Utt_DelayConf(st);
                    E.Utt_Start(st+1)     = E.Utt_Start(st);
                    E.Utt_End(st+1)       = E.Utt_End(st);
                    E.UttSearch_Start(st+1) = E.Utt_Start(st);
                    E.UttSearch_End(st+1)   = E.Utt_End(st);
                end
                E.Nutterances = E.Nutterances + 1;
                E.Utt_DelayEst(u) = ED1;  E.Utt_Delay(u) = D1;  E.Utt_DelayConf(u) = DC1;
                E.Utt_DelayEst(u+1) = ED2; E.Utt_Delay(u+1) = D2; E.Utt_DelayConf(u+1) = DC2;
                E.UttSearch_Start(u+1) = E.UttSearch_Start(u);
                E.UttSearch_End(u+1) = E.UttSearch_End(u);
                if D2 < D1
                    E.Utt_Start(u) = uS;     E.Utt_End(u) = BP;
                    E.Utt_Start(u+1) = BP;   E.Utt_End(u+1) = uE;
                else
                    E.Utt_Start(u) = uS;
                    E.Utt_End(u) = BP + fix((D2 - D1) / (2 * C.DS));
                    E.Utt_Start(u+1) = BP - fix((D2 - D1) / (2 * C.DS));
                    E.Utt_End(u+1) = uE;
                end
                if (E.Utt_Start(u) - C.SB) * C.DS + D1 < 0
                    E.Utt_Start(u) = C.SB + fix((C.DS - 1 - D1) / C.DS);
                end
                if E.Utt_End(u+1) * C.DS + D2 > d.Nsamples - C.SB * C.DS
                    E.Utt_End(u+1) = fix((d.Nsamples - D2) / C.DS) - C.SB;
                end
            else
                u = u + 1;
            end
        else
            u = u + 1;
        end
    end
end

function [bED1, bD1, bDC1, bED2, bD2, bDC2, bBP] = split_align(r, d, uS, sS, sE, uE, dEst, dConf, C)
    N = C.AlignNfft;
    kernel = N / 64;
    bED1 = 0; bD1 = 0; bDC1 = 0; bED2 = 0; bD2 = 0; bDC2 = 0; bBP = 0;
    uLen = sE - sS;
    Delta = N / (4 * C.DS);
    Step = fix((0.801 * uLen + 40 * Delta - 1) / (40 * Delta)) * Delta;
    Pad = fix(uLen / 10);
    if Pad < 75, Pad = 75; end
    BPs = sS + Pad;
    nb = 0;
    while true
        nb = nb + 1;
        BPs(nb+1) = BPs(nb) + Step;
        if ~((BPs(nb+1) <= (sE - Pad)) && (nb < 40)), break; end
    end
    if nb <= 0, return; end
    BPs = BPs(1:nb);
    ED1 = zeros(1, nb); ED2 = zeros(1, nb);
    for b = 1:nb
        ED1(b) = crude_align_test(r, d, dEst, uS, BPs(b), C);
        ED2(b) = crude_align_test(r, d, dEst, BPs(b), uE, C);
    end

    % ---- forward (first part) --------------------------------------------
    D1 = zeros(1, nb); DC1 = -2 * ones(1, nb);
    for est = unique(ED1)
        startr = uS * C.DS;
        startd = startr + est;
        if startd < 0, startr = -est; startd = 0; end
        maxbp = max(BPs(ED1 == est));
        nf = 0;
        while (startd + nf*N/4 + N <= d.Nsamples) && (startr + nf*N/4 + N <= maxbp * C.DS)
            nf = nf + 1;
        end
        sr = startr + (0:nf-1) * N/4;
        [pk, wt] = xcorr_peaks(r, d, sr, startd + (0:nf-1) * N/4, C);
        for b = find(ED1 == est)
            use = (sr + N) <= BPs(b) * C.DS;
            [D1(b), DC1(b)] = hist_peak(pk(:, use), wt(use), kernel, est, N);
        end
    end
    % ---- backward (second part) ------------------------------------------
    D2 = zeros(1, nb);
    DC2 = zeros(1, nb);
    DC2(DC1 > dConf) = -2;
    todo = find(DC2 <= -2);
    for est = unique(ED2(todo))
        startr = uE * C.DS - N;
        startd = startr + est;
        if startd + N > d.Nsamples
            startd = d.Nsamples - N;
            startr = startd - est;
        end
        minbp = min(BPs(todo(ED2(todo) == est)));
        nf = 0;
        while (startd - nf*N/4 >= 0) && (startr - nf*N/4 >= minbp * C.DS)
            nf = nf + 1;
        end
        sr = startr - (0:nf-1) * N/4;
        [pk, wt] = xcorr_peaks(r, d, sr, startd - (0:nf-1) * N/4, C);
        for b = todo(ED2(todo) == est)
            use = sr >= BPs(b) * C.DS;
            [D2(b), DC2(b)] = hist_peak(pk(:, use), wt(use), kernel, est, N);
        end
    end
    for b = 1:nb
        if abs(D2(b) - D1(b)) >= C.DS && (DC1(b) + DC2(b)) > (bDC1 + bDC2) && ...
                DC1(b) > dConf && DC2(b) > dConf
            bED1 = ED1(b); bD1 = D1(b); bDC1 = DC1(b);
            bED2 = ED2(b); bD2 = D2(b); bDC2 = DC2(b);
            bBP = BPs(b);
        end
    end
end

function [D, DC] = hist_peak(pk, wt, kernel, est, N)
    A = double(pk) * (wt(:) / kernel);
    Hsum = sum(A) * kernel;
    H = circ_tri_smooth(A, kernel) * kernel;
    [vmax, I] = max(H);
    Imax = I - 1;
    if vmax <= 0, Imax = 0; vmax = 0; end
    if Imax >= N/2, Imax = Imax - N; end
    D = est + Imax;
    if Hsum > 0, DC = vmax / Hsum; else, DC = 0; end
end

% =========================================================================
%  Perceptual model
% =========================================================================
function P = bark_spectra(data, starts, C)
    Nf = C.Nf;
    nf = numel(starts);
    P = zeros(C.Nb, nf);
    if nf == 0, return; end
    idx = (0:Nf-1)';
    X = fft(data(idx + starts(:)' + 1) .* repmat(hann_periodic(Nf), 1, nf));
    S = abs(X(1:Nf/2, :)).^2;
    S(1, :) = 0;
    P = C.W * S;
end

function L = intensity_warping(ppd, C)
    h = ones(C.Nb, 1);
    lo = C.bark_centre(:) < 4;
    h(lo) = 6 ./ (C.bark_centre(lo)' + 2);
    h(h > 2) = 2;
    zp = 0.23 * h.^0.15;
    th = repmat(C.abs_thresh(:), 1, size(ppd, 2));
    zpm = repmat(zp, 1, size(ppd, 2));
    L = ((th / 0.5).^zpm) .* ((0.5 + 0.5 * ppd ./ th).^zpm - 1);
    L(ppd <= th) = 0;
    L = L * C.Sl;
end

function v = pseudo_lp(x, p, C)
    w = repmat(C.bark_width(2:end)', 1, size(x, 2));
    tw = sum(C.bark_width(2:end));
    v = (sum((abs(x(2:end, :)) .* w).^p, 1) / tw).^(1/p) * tw;
end

function [fd, fda] = frame_disturbances(pr, pd, C, oldScale)
% pr, pd : Bark power densities (ref already freq-compensated) for a run of
% consecutive frames.  Applies the gain compensation, loudness transform,
% dead zone and asymmetry factor; returns per-frame disturbances.
    nf = size(pr, 2);
    th = repmat(C.abs_thresh(:), 1, nf);
    tar = sum(pr(2:end, :) .* (pr(2:end, :) > th(2:end, :)), 1);
    tad = sum(pd(2:end, :) .* (pd(2:end, :) > th(2:end, :)), 1);
    for f = 1:nf
        scale = (tar(f) + 5e3) / (tad(f) + 5e3);
        if ~isempty(oldScale)
            scale = 0.2 * oldScale + 0.8 * scale;
        end
        oldScale = scale;
        scale = min(max(scale, 3e-4), 5);
        pd(:, f) = pd(:, f) * scale;
    end
    Lr = intensity_warping(pr, C);
    Ld = intensity_warping(pd, C);
    D = Ld - Lr;
    m = 0.25 * min(Ld, Lr);
    D = (D - m) .* (D > m) + (D + m) .* (D < -m);
    fd = pseudo_lp(D, 2, C);
    ratio = ((pd + 50) ./ (pr + 50)).^1.2;
    ratio(ratio > 12) = 12;
    ratio(ratio < 3) = 0;
    fda = pseudo_lp(D .* ratio, 1, C);
end

function raw = psychoacoustic_model(r, d, E, C)
    SBD  = C.SB * C.DS;
    maxN = max(r.Nsamples, d.Nsamples);
    Nf   = C.Nf;
    hop  = Nf / 2;
    crit = 500;

    % skip leading / trailing digital silence of the reference
    half = fix(maxN / 2);
    a = abs(r.data);
    s5 = filter(ones(5, 1), 1, a);                  % s5(k) = sum a(k-4..k)
    pos = SBD + (0:half) ;                           % C start index
    v = s5(pos + 5);
    k = find(v >= crit, 1);
    if isempty(k), skip_start = half; else, skip_start = min(k - 1, half); end
    base = maxN - SBD + C.DPAD - 1;                  % C index of last sample
    pos = base - (0:half);
    v = s5(pos + 1);                                 % sum a(pos-4 .. pos)
    k = find(v >= crit, 1);
    if isempty(k), skip_end = half; else, skip_end = min(k - 1, half); end

    start_frame = fix(skip_start / hop);
    stop_frame  = fix((maxN - 2*SBD + C.DPAD - skip_end) / hop) - 1;
    nfr = stop_frame + 1;

    % per-frame delay from the utterance table
    Nu = E.Nutterances;
    starts_ref = SBD + (0:stop_frame) * hop;
    starts_deg = starts_ref + utt_delay_at(starts_ref, E, C);

    ppd_ref = bark_spectra(r.data, starts_ref, C);
    ok = (starts_deg > 0) & (starts_deg + Nf < maxN + C.DPAD);
    ppd_deg = zeros(C.Nb, nfr);
    ppd_deg(:, ok) = bark_spectra(d.data, starts_deg(ok), C);

    th = repmat(C.abs_thresh(:), 1, nfr);
    tot_ref100 = sum(ppd_ref(2:end, :) .* (ppd_ref(2:end, :) > 100 * th(2:end, :)), 1);
    silent = tot_ref100 < 1e7;

    % frequency response compensation of the reference
    ntot = fix((maxN - 2*SBD + C.DPAD) / hop) - 1;
    avg_ref = sum(ppd_ref(:, ~silent) .* (ppd_ref(:, ~silent) > 100 * th(:, ~silent)), 2) / ntot;
    avg_deg = sum(ppd_deg(:, ~silent) .* (ppd_deg(:, ~silent) > 100 * th(:, ~silent)), 2) / ntot;
    x = (avg_deg + 1000) ./ (avg_ref + 1000);
    x(x > 100) = 100;
    x(x < 0.01) = 0.01;
    ppd_ref = ppd_ref .* repmat(x, 1, nfr);

    total_power_ref = sum(ppd_ref(2:end, :) .* (ppd_ref(2:end, :) > th(2:end, :)), 1);
    [fd, fda] = frame_disturbances(ppd_ref, ppd_deg, C, []);
    there_is_bad = any(fd > 30);

    % frames skipped because of a large negative delay jump
    for u = 2:Nu
        frame1 = fix(((E.Utt_Start(u) - C.SB) * C.DS + E.Utt_Delay(u)) / hop);
        j = fix(((E.Utt_End(u-1) - C.SB) * C.DS + E.Utt_Delay(u-1)) / hop);
        jump = E.Utt_Delay(u) - E.Utt_Delay(u-1);
        if frame1 > j, frame1 = j; end
        if frame1 < 0, frame1 = 0; end
        if jump < -hop
            frame2 = fix(((E.Utt_Start(u) - C.SB) * C.DS + max(0, abs(jump))) / hop) + 1;
            for f = frame1:frame2
                if f < stop_frame
                    fd(f+1) = 0;
                    fda(f+1) = 0;
                end
            end
        end
    end

    if there_is_bad
        % degraded signal with per-utterance delays applied
        nn = C.DPAD + maxN;
        tweaked = zeros(nn, 1);
        i = (SBD:nn-SBD-1);
        j = i + utt_delay_at(i, E, C);
        j(j < SBD) = SBD;
        j(j >= nn - SBD) = nn - SBD - 1;
        tweaked(i + 1) = d.data(j + 1);

        bad = fd > 30;
        bad(1) = false;
        smeared = false(1, nfr);
        for f = 2:stop_frame-3
            smeared(f+1) = min(max(bad(f-1:f+1)), max(bad(f+1:f+3)));
        end
        % bad intervals
        bstart = []; bstop = [];
        f = 0;
        while f <= stop_frame
            while f <= stop_frame && ~smeared(f+1), f = f + 1; end
            if f <= stop_frame
                s0 = f;
                while f <= stop_frame && smeared(f+1), f = f + 1; end
                if f <= stop_frame
                    if f - s0 >= 5
                        bstart(end+1) = s0; %#ok<AGROW>
                        bstop(end+1) = f;   %#ok<AGROW>
                    end
                end
            end
        end
        if ~isempty(bstart)
            srange = 4 * Nf;
            dbl = tweaked;
            for b = 1:numel(bstart)
                ss = bstart(b) * hop + SBD;
                se = bstop(b) * hop + Nf + SBD;
                ns = se - ss;
                refseg = [zeros(srange, 1); r.data(ss+1:ss+ns); zeros(srange, 1)];
                jj = ss - srange + (0:2*srange+ns-1)';
                lim = maxN - SBD + C.DPAD;
                jj(jj < SBD) = SBD;
                jj(jj >= lim) = lim - 1;
                degseg = tweaked(jj + 1);
                [dly, corr] = compute_delay(refseg, degseg, srange);
                if corr < 0.5, dly = 0; end
                ii = (ss:se-1)';
                jj = ii + dly;
                jj(jj < 0) = 0;
                jj(jj >= maxN) = maxN - 1;
                dbl(ii + 1) = tweaked(jj + 1);
            end
            for b = 1:numel(bstart)
                fr = bstart(b):bstop(b)-1;
                pdb = bark_spectra(dbl, SBD + fr * hop, C);
                [fd2, fda2] = frame_disturbances(ppd_ref(:, fr+1), pdb, C, 1);
                fd(fr+1) = min(fd(fr+1), fd2);
                fda(fr+1) = min(fda(fr+1), fda2);
            end
        end
    end

    % time weighting (long files) and aggregation
    tw = ones(1, nfr);
    if nfr > 1000
        n = fix((maxN - 2*SBD) / hop) - 1;
        twf = min((n - 1000) / 5500, 0.5);
        tw = (1 - twf) + twf * (0:stop_frame) / n;
    end
    h = ((total_power_ref + 1e5) / 1e7).^0.04;
    fd = min(fd ./ h, 45);
    fda = min(fda ./ h, 45);
    d_ind = lpq_weight(start_frame, stop_frame, 6, 2, fd, tw);
    a_ind = lpq_weight(start_frame, stop_frame, 6, 2, fda, tw);
    raw = 4.5 - 0.1 * d_ind - 0.0309 * a_ind;
end

function dl = utt_delay_at(pos, E, C)
% Delay of the last utterance whose start is <= pos (utterance 1 if none).
    u = zeros(size(pos));
    for k = 1:E.Nutterances
        u(pos >= E.Utt_Start(k) * C.DS) = k;
    end
    u(u == 0) = 1;
    dl = E.Utt_Delay(u);
    dl = reshape(dl, size(pos));
end

function [best, maxc] = compute_delay(ts1, ts2, srange)
    n = numel(ts1);
    P = nextpow2_c(2 * n);
    p1 = sum(ts1.^2) / P;
    p2 = sum(ts2.^2) / P;
    best = 0; maxc = 0;
    if p1 <= 1e-6 || p2 <= 1e-6, return; end
    nrm = sqrt(p1 * p2);
    x1 = zeros(P, 1); x2 = zeros(P, 1);
    x1(1:n) = abs(ts1); x2(1:n) = abs(ts2);
    y = real(ifft(conj(fft(x1) / P) .* fft(x2)));
    lags = [(-srange:-1) + P, 0:srange-1];
    vals = abs(y(lags + 1)) / nrm;
    shifts = [-srange:-1, 0:srange-1];
    [maxc, k] = max(vals);
    best = shifts(k);
end

function v = lpq_weight(f0, f1, ps, pt, fdist, tw)
    rt = 0; tot = 0;
    for s = f0:10:f1
        fr = s:min(s+19, f1);
        rs = (sum(fdist(fr+1).^ps) / 20)^(1/ps);
        rt = rt + (tw(s - f0 + 1) * rs)^pt;
        tot = tot + tw(s - f0 + 1)^pt;
    end
    v = (rt / tot)^(1/pt);
end

% ========================================================================
% src/metrics/report_metrics.m
% ========================================================================
function report_metrics(title_str, clean, noisy, enh, fs)
%REPORT_METRICS  Print SNR / STOI / PESQ of the noisy and the enhanced signal.
    a = evaluate_pair(clean, noisy, fs);
    b = evaluate_pair(clean, enh, fs);
    fprintf(' %s:\n', title_str);
    fprintf('   SNR     %7.2f dB -> %7.2f dB\n', a(1), b(1));
    fprintf('   STOI    %7.3f    -> %7.3f\n', a(2), b(2));
    fprintf('   PESQ-WB %7.2f    -> %7.2f\n', a(3), b(3));
    fprintf('   PESQ-NB %7.2f    -> %7.2f\n', a(4), b(4));
end

% ========================================================================
% src/metrics/snr_metrics.m
% ========================================================================
function m = snr_metrics(clean, est, fs)
%SNR_METRICS  Waveform-level quality measures against a clean reference.
%
%   m = snr_metrics(clean, est, fs)
%     m.snr    : global SNR (dB)          10log10(|s|^2 / |s - est|^2)
%     m.segsnr : segmental SNR (dB), 32 ms frames, each clamped to [-10, 35]
%     m.sisdr  : scale-invariant SDR (dB)
    s = clean(:);
    y = est(:);
    n = min(numel(s), numel(y));
    s = s(1:n);
    y = y(1:n);
    m.snr = 10 * log10(sum(s.^2) / max(sum((s - y).^2), eps));

    N = round(0.032 * fs); H = round(N / 2);
    starts = 1:H:(n - N + 1);
    v = zeros(numel(starts), 1);
    for i = 1:numel(starts)
        a = s(starts(i):starts(i)+N-1);
        e = a - y(starts(i):starts(i)+N-1);
        v(i) = min(max(10 * log10(sum(a.^2) / (sum(e.^2) + eps) + eps), -10), 35);
    end
    m.segsnr = mean(v);

    a = (y' * s) / max(s' * s, eps);
    t = a * s;
    m.sisdr = 10 * log10(sum(t.^2) / max(sum((y - t).^2), eps));
end

% ========================================================================
% src/metrics/stoi_score.m
% ========================================================================
function d = stoi_score(clean, processed, fs, extended)
%STOI_SCORE  Short-Time Objective Intelligibility (STOI) and extended STOI.
%
%   d = stoi_score(clean, processed, fs)          classic STOI  [1]
%   d = stoi_score(clean, processed, fs, true)    extended STOI [2]
%
%   clean     : clean reference speech (vector)
%   processed : noisy or enhanced speech, time-aligned with clean
%   fs        : sampling rate in Hz (signals are resampled to 10 kHz)
%
%   Returns a value in ~[0, 1]; higher = more intelligible.  Toolbox-free
%   re-implementation of the algorithm in [1]/[2]; it reproduces the
%   reference implementation (pystoi / Taal's MATLAB code) to within
%   numerical precision.
%
%   [1] C.H. Taal, R.C. Hendriks, R. Heusdens, J. Jensen, "An algorithm for
%       intelligibility prediction of time-frequency weighted noisy speech",
%       IEEE Trans. ASLP, 19(7), 2011.
%   [2] J. Jensen, C.H. Taal, "An algorithm for predicting the
%       intelligibility of speech masked by modulated noise maskers",
%       IEEE/ACM Trans. ASLP, 24(11), 2016.

    if nargin < 4, extended = false; end

    x = double(clean(:));
    y = double(processed(:));
    n = min(numel(x), numel(y));
    x = x(1:n);
    y = y(1:n);

    FS      = 10000;   % internal sampling rate
    NFRAME  = 256;     % window length (25.6 ms)
    NFFT    = 512;
    NUMBAND = 15;      % one-third octave bands
    MINFREQ = 150;     % centre of first band (Hz)
    N       = 30;      % frames per intermediate segment (384 ms)
    BETA    = -15;     % lower SDR bound (dB)
    DYN     = 40;      % speech dynamic range (dB)

    if fs ~= FS
        x = resample_k(x, FS, fs);
        y = resample_k(y, FS, fs);
    end

    [x, y] = remove_silent_frames(x, y, DYN, NFRAME, NFRAME/2);

    X = stdft(x, NFRAME, NFRAME/2, NFFT);
    Y = stdft(y, NFRAME, NFRAME/2, NFFT);
    if size(X, 2) < N
        warning('stoi_score:short', ...
            'Not enough speech frames for STOI (need >= %d). Returning NaN.', N);
        d = NaN;
        return;
    end

    OBM   = thirdoct(FS, NFFT, NUMBAND, MINFREQ);
    X_tob = sqrt(OBM * abs(X).^2);          % bands x frames
    Y_tob = sqrt(OBM * abs(Y).^2);

    nseg = size(X_tob, 2) - N + 1;
    J    = size(X_tob, 1);
    c    = 10^(-BETA / 20);
    dint = zeros(J, nseg);
    ext  = zeros(1, nseg);

    for m = 1:nseg
        Xs = X_tob(:, m:m+N-1);
        Ys = Y_tob(:, m:m+N-1);
        if extended
            xn = row_col_normalize(Xs);
            yn = row_col_normalize(Ys);
            ext(m) = sum(sum(xn .* yn)) / N;
        else
            alpha = sqrt(sum(Xs.^2, 2)) ./ (sqrt(sum(Ys.^2, 2)) + eps);
            Yp = min(Ys .* repmat(alpha, 1, N), Xs * (1 + c));
            Yp = Yp - repmat(mean(Yp, 2), 1, N);
            Xc = Xs - repmat(mean(Xs, 2), 1, N);
            Yp = Yp ./ repmat(sqrt(sum(Yp.^2, 2)) + eps, 1, N);
            Xc = Xc ./ repmat(sqrt(sum(Xc.^2, 2)) + eps, 1, N);
            dint(:, m) = sum(Xc .* Yp, 2);
        end
    end

    if extended
        d = mean(ext);
    else
        d = mean(dint(:));
    end
end

% -------------------------------------------------------------------------
function xn = row_col_normalize(x)
    xn = x - repmat(mean(x, 2), 1, size(x, 2));
    xn = xn ./ repmat(sqrt(sum(xn.^2, 2)) + eps, 1, size(x, 2));
    xn = xn - repmat(mean(xn, 1), size(x, 1), 1);
    xn = xn ./ repmat(sqrt(sum(xn.^2, 1)) + eps, size(x, 1), 1);
end

function w = hanning_sym(N)
    w = 0.5 * (1 - cos(2 * pi * (1:N)' / (N + 1)));   % = hanning(N)
end

function S = stdft(x, N, K, NFFT)
% Short-time DFT, frames start at 1:K:(length(x)-N), bins 0..NFFT/2.
    starts = 1:K:(numel(x) - N);
    if isempty(starts)
        S = zeros(NFFT/2 + 1, 0);
        return;
    end
    idx = repmat((0:N-1)', 1, numel(starts)) + repmat(starts, N, 1);
    fr  = x(idx) .* repmat(hanning_sym(N), 1, numel(starts));
    S   = fft(fr, NFFT, 1);
    S   = S(1:NFFT/2 + 1, :);
end

function [xs, ys] = remove_silent_frames(x, y, dyn, N, K)
% Drop frames whose clean-speech energy is > dyn dB below the loudest frame.
    starts = 1:K:(numel(x) - N);
    w   = hanning_sym(N);
    idx = repmat((0:N-1)', 1, numel(starts)) + repmat(starts, N, 1);
    xf  = x(idx) .* repmat(w, 1, numel(starts));
    yf  = y(idx) .* repmat(w, 1, numel(starts));
    e   = 20 * log10(sqrt(sum(xf.^2, 1)) + eps);
    keep = (e - max(e) + dyn) > 0;
    xf = xf(:, keep);
    yf = yf(:, keep);
    nk = size(xf, 2);
    if nk == 0
        xs = zeros(0, 1); ys = zeros(0, 1);
        return;
    end
    pos = repmat((1:N)', 1, nk) + repmat((0:nk-1) * K, N, 1);
    len = (nk - 1) * K + N;
    xs  = accumarray(pos(:), xf(:), [len 1]);
    ys  = accumarray(pos(:), yf(:), [len 1]);
end

function A = thirdoct(fs, nfft, num_bands, min_freq)
% One-third octave band matrix (bands x (nfft/2+1)).
    f  = linspace(0, fs, nfft + 1);
    f  = f(1:nfft/2 + 1);
    k  = 0:num_bands-1;
    fl = min_freq * 2.^((2*k - 1) / 6);
    fh = min_freq * 2.^((2*k + 1) / 6);
    A  = zeros(num_bands, numel(f));
    for i = 1:num_bands
        [~, lo] = min((f - fl(i)).^2);
        [~, hi] = min((f - fh(i)).^2);
        A(i, lo:hi-1) = 1;
    end
end

% ========================================================================
% src/utils/play_audio_file.m
% ========================================================================
function play_audio_file(v, fs, label)
%PLAY_AUDIO_FILE  Play a signal (normalised) and wait until it has finished.
    fprintf(' Playing %s ...\n', label);
    try
        sound(v / max(abs(v)) * 0.9, fs);
        pause(numel(v) / fs + 0.5);
    catch
        fprintf('   (no audio device available - listen to the WAV files in results/)\n');
    end
end

% ========================================================================
% src/utils/plot_spectrograms.m
% ========================================================================
function plot_spectrograms(x, y, fs, ttl)
%PLOT_SPECTROGRAMS  Noisy vs. enhanced spectrogram (same colour scale).
    if nargin < 4, ttl = ''; end
    [Sx, t, f] = spec_db(x, fs);
    Sy = spec_db(y, fs);
    top = max(Sx(:));
    figure('Name', ['ANC: ' ttl], 'Color', 'w');
    subplot(2, 1, 1);
    imagesc(t, f, Sx); axis xy; clim([top - 80, top]); colormap(jet); colorbar;
    title(['Noisy input: ' ttl], 'Interpreter', 'none'); ylabel('Frequency (kHz)');
    subplot(2, 1, 2);
    imagesc(t, f, Sy); axis xy; clim([top - 80, top]); colormap(jet); colorbar;
    title('Enhanced output (AI/ML adaptive noise cancellation)');
    ylabel('Frequency (kHz)'); xlabel('Time (s)');
end

function [S, t, f] = spec_db(x, fs)
    N = 512; R = 128;
    x = x(:);
    if numel(x) < N, x(N) = 0; end
    w = 0.5 - 0.5 * cos(2 * pi * (0:N-1)' / N);
    nf = floor((numel(x) - N) / R) + 1;
    idx = repmat((1:N)', 1, nf) + repmat((0:nf-1) * R, N, 1);
    X = fft(x(idx) .* repmat(w, 1, nf));
    S = 20 * log10(abs(X(1:N/2+1, :)) + 1e-9);
    t = ((0:nf-1) * R + N/2) / fs;
    f = (0:N/2) * fs / N / 1000;
end

% ========================================================================
% src/utils/read_audio.m
% ========================================================================
function [x, fs] = read_audio(file)
%READ_AUDIO  audioread() that also accepts .mpeg / .mpg files.
%   MATLAB chooses the decoder from the file extension, so an MP3 stream
%   saved as .mpeg (like defence_soundMG1.mpeg) is copied to a temporary
%   .mp3 file first.  Returns all channels as double.
    [~, ~, ext] = fileparts(file);
    if any(strcmpi(ext, {'.mpeg', '.mpg', '.mpga', '.mp2'}))
        tmp = [tempname '.mp3'];
        copyfile(file, tmp);
        try
            [x, fs] = audioread(tmp);
        catch err
            delete(tmp);
            rethrow(err);
        end
        delete(tmp);
    else
        [x, fs] = audioread(file);
    end
    x = double(x);
end

% ========================================================================
% src/utils/resample_k.m
% ========================================================================
function y = resample_k(x, fs_out, fs_in)
%RESAMPLE_K  Toolbox-free polyphase resampler (Kaiser-windowed sinc, 60 dB).
%
%   y = resample_k(x, fs_out, fs_in) converts the column/row vector x from
%   sampling rate fs_in to fs_out (both integers).  The anti-aliasing
%   filter is the same Kaiser-windowed sinc design used by GNU Octave's
%   resample() (and by pystoi), so STOI/PESQ values computed with this
%   project match the reference Python implementations.  No Signal
%   Processing Toolbox is required.
%
%   Output length = ceil(length(x) * fs_out / fs_in), zero-phase aligned.

    if fs_out == fs_in
        y = x;
        return;
    end
    isrow_in = isrow(x);
    x = double(x(:));

    g = gcd(round(fs_out), round(fs_in));
    p = round(fs_out) / g;
    q = round(fs_in) / g;

    % ---- anti-aliasing filter (Kaiser-windowed ideal low-pass) ----------
    rejection_dB      = 60;
    stopband_cutoff_f = 1 / (2 * max(p, q));
    roll_off_width    = stopband_cutoff_f / 10;
    L    = ceil((rejection_dB - 8) / (28.714 * roll_off_width));
    t    = (-L:L)';
    arg  = 2 * stopband_cutoff_f * t;
    sincv = ones(size(arg));
    nz   = arg ~= 0;
    sincv(nz) = sin(pi * arg(nz)) ./ (pi * arg(nz));
    beta = 0.1102 * (rejection_dB - 8.7);
    M    = 2 * L + 1;
    n    = (0:M-1)';
    kais = besseli(0, beta * sqrt(1 - (2 * n / (M - 1) - 1).^2)) / besseli(0, beta);
    h    = kais .* (2 * p * stopband_cutoff_f * sincv);
    h    = p * h / sum(h);                  % exact unity DC gain after upsampling

    % ---- polyphase filtering: y[m] = sum_n x[n] h[m*q - n*p + L] ---------
    Lx = numel(x);
    Lh = numel(h);
    Ly = ceil(Lx * p / q);
    m    = (0:Ly-1)';
    tt   = m * q + L;
    nmax = floor(tt / p);
    r    = tt - nmax * p;                   % polyphase branch (0..p-1)
    J    = ceil(Lh / p);
    hp   = zeros(p * J, 1);
    hp(1:Lh) = h;
    H    = reshape(hp, p, J);               % H(r+1, j+1) = h(r + j*p + 1)

    y = zeros(Ly, 1);
    for j = 0:J-1
        nidx  = nmax - j;
        valid = (nidx >= 0) & (nidx <= Lx - 1);
        if ~any(valid), continue; end
        coef  = H(r(valid) + 1, j + 1);
        y(valid) = y(valid) + coef .* x(nidx(valid) + 1);
    end

    if isrow_in
        y = y.';
    end
end
