/*
 * se_programs.h - serial engine programs, generated by tools/se_asm.py.
 * Do not edit: change the .se files in programs/ and run tools/build_programs.sh.
 *
 * Load a program:  for (i = 0; i < SE_PROG_X_LEN; i++)
 *                      PROG[SE_PROG_X_ORIGIN + i] = se_prog_x[i];
 * then write SMs_CLKDIV / PINCTRL / SHIFTCTRL, RESTART and enable the SM.
 */
#ifndef SE_PROGRAMS_H
#define SE_PROGRAMS_H

#include <stdint.h>

/* uart_tx: programs/uart_tx.se (7 words at 0) */
static const uint16_t se_prog_uart_tx[] = {
    0x80c0, 0xa027, 0xa700, 0x6601, 0x0043, 0xa701, 0x0000,
};
#define SE_PROG_UART_TX_ORIGIN    0
#define SE_PROG_UART_TX_LEN       7
#define SE_PROG_UART_TX_CLKDIV    0x006c8000u
#define SE_PROG_UART_TX_PINCTRL   0x02200015u
#define SE_PROG_UART_TX_SHIFTCTRL 0x00000000u

#endif /* SE_PROGRAMS_H */
