#!/usr/bin/env python3
"""
Bundle main_defence_anc.m and every function in src/ into ONE MATLAB file,
defence_anc_all_in_one.m (a function file with sub-functions, which runs in
MATLAB and GNU Octave).  Usage:  python tools/make_single_file.py
"""
import glob, os, re

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
main = open(os.path.join(root, "main_defence_anc.m")).read()

header, body = main.split("clear; close all; clc;", 1)
body = body.replace("addpath(genpath(fullfile(root, 'src')));\n", "")
out = ["function defence_anc_all_in_one()",
       header.rstrip().replace("%% MAIN_DEFENCE_ANC", "%% DEFENCE_ANC_ALL_IN_ONE")
              .replace("type  main_defence_anc", "type  defence_anc_all_in_one"),
       "%  (single-file bundle generated by tools/make_single_file.py - identical",
       "%   code to main_defence_anc.m + src/*; keep models/defence_gru.mat next",
       "%   to this file or in ./models to enable the AI/ML stage)",
       "",
       "close all; clc;",
       body.rstrip(),
       "end", ""]

names = set()
for f in sorted(glob.glob(os.path.join(root, "src", "**", "*.m"), recursive=True)):
    txt = open(f).read().rstrip() + "\n"
    for n in re.findall(r"^function\s+(?:\[[^\]]*\]\s*=\s*|\w+\s*=\s*)?(\w+)", txt, re.M):
        if n in names:
            raise SystemExit(f"duplicate function name {n} in {f}")
        names.add(n)
    out.append("% " + "=" * 72)
    out.append("% " + os.path.relpath(f, root))
    out.append("% " + "=" * 72)
    out.append(txt)

dst = os.path.join(root, "defence_anc_all_in_one.m")
open(dst, "w").write("\n".join(out))
print(f"wrote {dst}: {len(names)} functions, {sum(1 for _ in open(dst))} lines")
